export interface DJ {
  id: string;
  name: string;
  artistName: string;
  contactDetails: string;
  location: string;
  creativeDisciplines: string;
  linksToWork: string;
  genre: string;
  timesBooked: number;
  mostRecentEvent: string;
  mostRecentEventDate: string;
}

function cleanValue(value: string): string {
  if (!value || value.trim() === "#ERROR!") return "";
  return value.trim();
}

function parseTimesBooked(value: string): number {
  const cleaned = cleanValue(value);
  const parsed = parseInt(cleaned, 10);
  return isNaN(parsed) ? 0 : parsed;
}

export const dummyDJs: DJ[] = [
  {
    id: "1",
    name: "Arun Dhanjal",
    artistName: "Zar",
    contactDetails: "adjzar@gmail.com",
    location: "London",
    creativeDisciplines: "DJ / Producer / Live performer",
    linksToWork: "https://linktr.ee/ajdzar",
    genre: "Multi genre",
    timesBooked: 5,
    mostRecentEvent: "Ministry of Sound",
    mostRecentEventDate: "",
  },
  {
    id: "2",
    name: "Saadaan Afghan",
    artistName: "Saadaan",
    contactDetails: "",
    location: "Coventry / London",
    creativeDisciplines: "DJ / Producer",
    linksToWork: "saadaan.bandcamp.com\nwaveplate.systems",
    genre: "140, Dubstep, Left Field Bass, 2-step/ukg, Hip Hop, Techno, Electro (sometimes House)",
    timesBooked: 1,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "3",
    name: "Michael Diamond",
    artistName: "Michael Diamond",
    contactDetails: "diamond.sounduk@gmail.com",
    location: "Oxford/London",
    creativeDisciplines: "DJ / Producer / Live performer",
    linksToWork: "https://soundcloud.com/michaeldiamonduk",
    genre: "Electronic, Jazz",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "4",
    name: "Sita Shah",
    artistName: "Sita Shah",
    contactDetails: "sitashahsworld@gmail.com",
    location: "London\nSometimes NYC",
    creativeDisciplines: "DJ / Presenter / learning to produce",
    linksToWork: "soundcloud.com/sitashahdj",
    genre: "Techno, hardcore, breaks, desi, bootlegs",
    timesBooked: 3,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "5",
    name: "Ral Daryanani",
    artistName: "Rainmann",
    contactDetails: "",
    location: "London",
    creativeDisciplines: "DJ / Producer / Live performer",
    linksToWork: "SoundCloud.com/rainm4nn",
    genre: "All",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "6",
    name: "Anisa Jackson",
    artistName: "Cardamami",
    contactDetails: "djcardamami@gmail.com",
    location: "NYC",
    creativeDisciplines: "DJ",
    linksToWork: "soundcloud.com/cardamami",
    genre: "All",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "7",
    name: "Mehar Bedi",
    artistName: "GoodMostlyBad",
    contactDetails: "mehar.bedi@gmail.com",
    location: "Doha",
    creativeDisciplines: "DJ /Producer",
    linksToWork: "soundcloud.com/goodmostlybad",
    genre: "ASS CLAPS ONLY (Hiphop,Afrobeats, Amapiano,UKG,Bass,Dancehall,Trap etc)",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "8",
    name: "Somin Griffin-Dave",
    artistName: "Somatic",
    contactDetails: "somin.somatic@gmail.com",
    location: "Exeter (Sometimes Bristol) but owns a car and is willing to travel.",
    creativeDisciplines: "DJ, Producer, Sound Designer, Sound Engineer.",
    linksToWork: "linktr.ee/somin_somatic",
    genre: "DnB, Jungle, Breakbeat, Garage, IDM, Experimental, Various other 4x4 genres, (Classic) Afrobeat, a touch of bossa and various other things.",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "9",
    name: "Josh de Silva",
    artistName: "Liyo (new project called RISE coming soon)",
    contactDetails: "",
    location: "London",
    creativeDisciplines: "DJ",
    linksToWork: "https://soundcloud.com/liyomusic",
    genre: "Techno, Dubstep, Jungle, Garage, Electro etc etc",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "10",
    name: "Freshta Ebrahim",
    artistName: "Freshta",
    contactDetails: "freshtainfo@gmail.com",
    location: "London",
    creativeDisciplines: "DJ and Radio Host",
    linksToWork: "linktr.ee/_freshta",
    genre: "Grime, Dubstep, Leftfield Bass, Breaks, Hard Drum",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "11",
    name: "Jaedan Gowthaman",
    artistName: "GoldTooth",
    contactDetails: "dj@goldtooth.uk",
    location: "London",
    creativeDisciplines: "DJ, Producer",
    linksToWork: "SoundCloud.com/goldtooth_dj",
    genre: "Grime, Dubstep, UK Funky, Garage, Drill, SA House, afrohouse, kuduro\n\nAlso specialise in vinyl sets",
    timesBooked: 1,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "12",
    name: "Roop",
    artistName: "Temujin",
    contactDetails: "temujin.ldn@gmail.com",
    location: "London",
    creativeDisciplines: "DJ + Radio (producer soon come)",
    linksToWork: "soundcloud.com/temujin-ldn",
    genre: "UK underground dance - Bass, Techno, Breaks, Garage, Jungle, Dubstep, Grime (heavy on the percs and dub)",
    timesBooked: 3,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "13",
    name: "Dhillon Chhabra",
    artistName: "Darama",
    contactDetails: "darama@daytimers.org",
    location: "London\nSometimes Manchester/Leeds",
    creativeDisciplines: "DJ, producer",
    linksToWork: "https://soundcloud.com/daramadj",
    genre: "UK Bass, anything percussive, Grime, Drill, House,Techno, UK Funky, UKG, Disco",
    timesBooked: 2,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "14",
    name: "Saachi",
    artistName: "Saachi",
    contactDetails: "djsaachi@hotmail.com",
    location: "London",
    creativeDisciplines: "DJ",
    linksToWork: "https://www.mixcloud.com/baachisains/\n\nhttps://soundcloud.com/saachi-bains",
    genre: "House (sometimes electro & Ghettotech)",
    timesBooked: 5,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "15",
    name: "Kishan Thakrar",
    artistName: "Kishan",
    contactDetails: "music@kishan.co.uk",
    location: "London",
    creativeDisciplines: "DJ & Producer",
    linksToWork: "https://www.liinks.co/kishan\n\nhttps://soundcloud.com/kishanthakrar",
    genre: "UKG, House, Hip Hop/Afrobeat, 140, Jungle, DnB etc",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "16",
    name: "Priya Majhail",
    artistName: "DJ PRIYA",
    contactDetails: "majpri95@gmail.com",
    location: "London/ Brighton",
    creativeDisciplines: "DJ",
    linksToWork: "https://soundcloud.com/deejaypriya",
    genre: "Reggaeton, Bashment, Dancehall, Funky",
    timesBooked: 2,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "17",
    name: "Simaran Patel",
    artistName: "Qwirk",
    contactDetails: "qwirkdubstep@gmail.com",
    location: "Manchester",
    creativeDisciplines: "DJ/Producer",
    linksToWork: "linktr.ee/qwirk\n\nhttps://soundcloud.com/qwirkk",
    genre: "Dubstep, Grime, Garage, Breakbeat, DnB, Footwork, Trap, Jungle",
    timesBooked: 2,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "18",
    name: "Rohan Rakhit",
    artistName: "Rohan Rakhit",
    contactDetails: "rohan@daytimers.org",
    location: "London",
    creativeDisciplines: "DJ/Presenter/Broadcaster",
    linksToWork: "https://www.mixcloud.com/rohan-rakhit/",
    genre: "Multi-genre",
    timesBooked: 6,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "19",
    name: "Jaskaran Notta",
    artistName: "Jaskkkkkkk",
    contactDetails: "jaskaran.notta97@gmail.com",
    location: "Birmingham",
    creativeDisciplines: "DJ",
    linksToWork: "https://soundcloud.app.goo.gl/QLnxd5BZitZF8YHx7",
    genre: "Electro, Ghetto, Italo, breakbeat, chugg (sometimes garage, disco)",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "20",
    name: "Kashif Majeed",
    artistName: "Ash Lovecraft",
    contactDetails: "ashlovecraftmusic@gmail.com",
    location: "Toronto",
    creativeDisciplines: "DJ/Producer",
    linksToWork: "HTTPS://www.soundcloud.com/ashlovecraft",
    genre: "Moombahton/Dancehall",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "21",
    name: "Adnan",
    artistName: "Adnan.Afghani",
    contactDetails: "",
    location: "London",
    creativeDisciplines: "DJ/producer/\nfield recorder",
    linksToWork: "@adnan1198 | Linktree",
    genre: "140/160 (techno/breaks/idm/dubstep)\n+experimental",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "22",
    name: "Sherwyn Appadu",
    artistName: "King Monday",
    contactDetails: "kxmonday@hotmail.com",
    location: "London",
    creativeDisciplines: "DJ / Producer / Live performer",
    linksToWork: "https://soundcloud.com/kingxmonday",
    genre: "Turkish Psychedelic Folk\nExperimental",
    timesBooked: 1,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "23",
    name: "Anandit Sachdev (Antariksh Records)",
    artistName: "Antariksh Daddy/\nAarAv",
    contactDetails: "contact@ananditsachdev.com",
    location: "Delhi",
    creativeDisciplines: "DJ/ Producer",
    linksToWork: "https://soundcloud.com/antarikshrecs (LABEL)\n\nhttps://soundcloud.com/anandit-sachdev (PERSONAL)",
    genre: "Electronic (Everything 110 to 160 BMP)\n\nVinyl only sets too.",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "24",
    name: "Debesh Mandal",
    artistName: "Mandle",
    contactDetails: "mandle.demain@gmail.com",
    location: "London / Manchester",
    creativeDisciplines: "DJ/Producer/Presenter",
    linksToWork: "https://soundcloud.com/djmandle",
    genre: "House, Techno, Breaks, Jungle, Disco",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "25",
    name: "Rea Chawhan",
    artistName: "REA",
    contactDetails: "",
    location: "Bristol/London/Madrid",
    creativeDisciplines: "DJ/Producer",
    linksToWork: "https://soundcloud.com/readnb",
    genre: "Dnb, Breaks/Footwork, UKG, UK Dubstep",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "26",
    name: "Rohit Tandon",
    artistName: "Sepoys",
    contactDetails: "basspradesh@gmail.com",
    location: "Vancouver, BC",
    creativeDisciplines: "DJ/Producer",
    linksToWork: "https://soundcloud.com/sepoys",
    genre: "Liquid DnB/ Jungle",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "27",
    name: "Provhat Rahman",
    artistName: "Provhat",
    contactDetails: "provhat@daytimers.org",
    location: "London",
    creativeDisciplines: "DJ/Producer",
    linksToWork: "-",
    genre: "UK Bass",
    timesBooked: 4,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "28",
    name: "Kavhan Karthik",
    artistName: "Mera Bhai",
    contactDetails: "merabhaiiimusic@gmail.com",
    location: "London",
    creativeDisciplines: "DJ/Producer/Multi-instrumentalist/Radio Host",
    linksToWork: "https://linktr.ee/merabhaiii",
    genre: "Detroit + Italo House + Disco,  Acid House, Techno, Breaks, Funk, UKG, Global Riddims. Vinyl only sets include - strictly UKG, 70s-80s Bollywood disco, world/int'l psych/funk/disco",
    timesBooked: 2,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "29",
    name: "Izzi Dickson",
    artistName: "Izzi",
    contactDetails: "phone: 07517223023",
    location: "Cambridge/London (student)",
    creativeDisciplines: "DJ",
    linksToWork: "Mixes/radio: https://soundcloud.app.goo.gl/aXWw6FdyUhNKSXZi6",
    genre: "UK bass, breaks, leftfield techno, hard drum, electro, jungle, footwork",
    timesBooked: 1,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "30",
    name: "Sita Shah",
    artistName: "Sita Shah",
    contactDetails: "7506229329",
    location: "London / New York",
    creativeDisciplines: "DJ, Aspiring Producer, Director, Conceptual Creative",
    linksToWork: "https://soundcloud.com/sitashahdj\nhttps://www.sitashahcreative.com/",
    genre: "Techno, edits, desi ... Anything fast and fun!",
    timesBooked: 2,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "31",
    name: "Sunayah Arshad",
    artistName: "Sunayah",
    contactDetails: "sunayah.arshad@gmail.com",
    location: "London",
    creativeDisciplines: "Producer (shoots + events), writer, sometimes DJ",
    linksToWork: "www.sunayah.co.uk",
    genre: "",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "32",
    name: "Iqra Nowshari",
    artistName: "Triqi",
    contactDetails: "",
    location: "Berlin, Germany",
    creativeDisciplines: "DJ",
    linksToWork: "www.soundcloud.com/triqi030",
    genre: "house, breaks, electro, techno, disco, soul, funk",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "33",
    name: "rea chawhan",
    artistName: "REA",
    contactDetails: "reamusickuk@gmail.com or +447402944409",
    location: "bristol",
    creativeDisciplines: "dj/producer",
    linksToWork: "https://soundcloud.com/reamusicuk, \n\nhttps://open.spotify.com/artist/1nhQOYji5l5jrGliSvMvc6?si=7hnX6-8fTJmcG_eLjG-qbQ, \n\nhttps://soundcloud.com/reamusicuk/rea-time-forthcoming-redacted/s-fzbi2E3WLaR?utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing\n\nhttps://soundcloud.com/reamusicuk/kangna-bootleg/s-ANLIYYBVCkc?utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing\n\nhttps://soundcloud.com/redactedbristol/rea-throe-over?utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing\n\nhttps://soundcloud.com/reamusicuk/quicksand-reas-ukg-mix/s-Ofbr841zK4a?utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing\n\n",
    genre: "ukg, drum and bass, breakbeat/footwork, dubstep",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "34",
    name: "Kush Varma",
    artistName: "KRMA",
    contactDetails: "email - krmabeats@gmail.com",
    location: "LA",
    creativeDisciplines: "Producer, DJ",
    linksToWork: "https://linktr.ee/krma.music",
    genre: "Electronic, trap, dnb, bass",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "35",
    name: "Rahul Dhulipala",
    artistName: "Solar Plexus",
    contactDetails: "7827157867",
    location: "London / South Wales",
    creativeDisciplines: "DJ",
    linksToWork: "https://soundcloud.app.goo.gl/i44Mavo4fsdjnxzf8",
    genre: "ukg / uk dubstep / grime / breaks / 160 / jungle",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "36",
    name: "Harry Basra",
    artistName: "Basra",
    contactDetails: "Harrybasra1@gmail.com",
    location: "London",
    creativeDisciplines: "DJ",
    linksToWork: "https://soundcloud.app.goo.gl/Yvtor8jbtP9kxs1w8",
    genre: "",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "37",
    name: "Gaia Ahuja",
    artistName: "G33",
    contactDetails: "gaiaahuja7@hotmail.com // 07845752577 // https://www.instagram.com/gaia_ia/",
    location: "Liverpool / London",
    creativeDisciplines: "DJ / presenter",
    linksToWork: "https://www.youtube.com/watch?v=iFqQZTupAqY https://www.instagram.com/p/CaU3bIGKTyR/\nhttps://www.youtube.com/watch?v=GSFsI7SXQ9k\nhttps://soundcloud.com/gggeethreethree/bbc-asian-network-pure-spice-guest-mix",
    genre: "UKG, UK funky, grime, bass, dancehall",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "38",
    name: "Himay",
    artistName: "Himay",
    contactDetails: "Himay.kumbhani89@gmail.com",
    location: "Mumbai",
    creativeDisciplines: "Dj, producer, graphic designer",
    linksToWork: "https://linktr.ee/heeemay",
    genre: "House",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "39",
    name: "Apoorv Khanna",
    artistName: "Shortsell",
    contactDetails: "",
    location: "India",
    creativeDisciplines: "DJ",
    linksToWork: "https://linktr.ee/shortsell",
    genre: "Genre agnostic",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "40",
    name: "Sasith Gamage",
    artistName: "IYRE",
    contactDetails: "94716558996",
    location: "Colombo, Sri Lanka",
    creativeDisciplines: "Producer/DJ",
    linksToWork: "https://youtu.be/xVYnI8jOShE\nhttps://youtu.be/ma0nEs2GU08\nhttps://youtu.be/uxJDLwxyePE\nhttps://youtu.be/jrmmYabx04s\nhttps://youtu.be/57P7vSPuh0c\nhttps://youtu.be/m6AQcVeCYWM\nhttps://ukf.com/words/iyre-is-proudly-putting-sri-lanka-on-the-drum-bass-map/31353\nhttps://ukf.com/news/ukf-future-vision-artists-revealed/32438\nhttps://mixmag.asia/read/iyre-sri-lanka-global-drumnbass-new-releases\nhttps://mixmag.asia/read/iyre-liquid-drumnbass-mixmag-asia-radio-sri-lanka-exclusive-mixes",
    genre: "Drum and Bass",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "41",
    name: "Jehan Bhesania",
    artistName: "Jayhaan",
    contactDetails: "",
    location: "Mumbai, India",
    creativeDisciplines: "Dj / Producer",
    linksToWork: "ghelo.biglink.to/jayhaan",
    genre: "Asian Underground / Open Format",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "42",
    name: "Itrat (Iti) Memon",
    artistName: "Iti",
    contactDetails: "iti@affix.management",
    location: "Brisbane, Australia (for now)",
    creativeDisciplines: "DJ, Producer, Live Electronic Performer, Label Director, Manager",
    linksToWork: "https://iti-mqn.bandcamp.com/album/curvework-vol-1-as-time-passes",
    genre: "UK Funky, Breaks, Electro, Garage, 2-step, ambient",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "43",
    name: "Shyam Anand",
    artistName: "Snad",
    contactDetails: "",
    location: "Philadelphia/Berlin",
    creativeDisciplines: "DJ/Producer",
    linksToWork: "soundcloud.com/snad",
    genre: "house, garage (New York, New Jersey and UK), good tech house",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "44",
    name: "Akhilan Singam",
    artistName: "Gasing",
    contactDetails: "IG: gasingraised // Tel: +60122969596 // Email: akhilan2512@gmail.com",
    location: "Kuala Lumpur (Moving to Bristol in August)",
    creativeDisciplines: "DJ",
    linksToWork: "https://www.mixcloud.com/gasingraised/\nhttps://soundcloud.com/gasingraised",
    genre: "House, Techno, Garage, Grime, Jungle",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "45",
    name: "Raj Chandrarajah",
    artistName: "Kai Kaspar",
    contactDetails: "7827225208",
    location: "Glasgow",
    creativeDisciplines: "DJ/Producer",
    linksToWork: "https://soundcloud.app.goo.gl/cCSTTNREucHxqDXy9",
    genre: "House, electro & acid",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "46",
    name: "Aniket Dabholkar",
    artistName: "Full Motion Disaster",
    contactDetails: "fullmotiondisaster@gmail.com",
    location: "Mumbai, India",
    creativeDisciplines: "DJ, Producer, Label Owner (Filth Inc.)",
    linksToWork: "https://soundcloud.com/filth-inc-official/full-motion-disaster-x-dm-90-no-respite",
    genre: "Ghettotech, Breaks, Electro, House, Hard Dance",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "47",
    name: "Dr Amit Dinesh Patel",
    artistName: "Dushume",
    contactDetails: "7790064378",
    location: "Leicester",
    creativeDisciplines: "Noise/ Experimental Sound Artist / DJ",
    linksToWork: "www.dushume.co.uk",
    genre: "Noise, Experimental Sound, Glitch, Electroacoustic music, Sound Art, Live Electronics",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "48",
    name: "Nik Sahdev",
    artistName: "Ghosty",
    contactDetails: "Dnbghosty@gmail.com",
    location: "Liverpool",
    creativeDisciplines: "DJ",
    linksToWork: "https://soundcloud.app.goo.gl/jvRkYtRdQbaamWh8A\nWww.Instagram.com/Nik.ghosty",
    genre: "Jungle, DnB",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "49",
    name: "Dani Wijesinghe",
    artistName: "ORDERLY ROOM",
    contactDetails: "wijesinghedani@gmail.com / 07999845101",
    location: "Bristol, UK",
    creativeDisciplines: "DJ, writer",
    linksToWork: "soundcloud.com/orderly-room",
    genre: "bass music, deconstructed club, hard drum, techno, noise, industril",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "50",
    name: "Vijay Patel",
    artistName: "JAY TAPES",
    contactDetails: "7939000149",
    location: "Wapping, London",
    creativeDisciplines: "DJ / Amateur Producer",
    linksToWork: "soundcloud.com/jaytapes",
    genre: "House, Techno, Electro, Breaks, Dubstep, Footwork, Reggaeton /Baile, Jungle, etc",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "51",
    name: "Pranam Mavahalli",
    artistName: "élan vital",
    contactDetails: "elanvitalbeats@gmail.com",
    location: "Manchester",
    creativeDisciplines: "Musician/producer/DJ",
    linksToWork: "https://open.spotify.com/artist/6PVOJqMGjo0XqIRuc3v1vs?si=gE1xPku1TUqkGhunC4NKhg",
    genre: "Breaks/electronic/jungle/beats",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "52",
    name: "Omer Tariq",
    artistName: "OT",
    contactDetails: "7940164390",
    location: "Bedford",
    creativeDisciplines: "Vinyl DJ",
    linksToWork: "https://m.mixcloud.com/ot/",
    genre: "Indian classical music",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "53",
    name: "Alvi",
    artistName: "Alvi Island",
    contactDetails: "7943222485",
    location: "London",
    creativeDisciplines: "Producer/DJ",
    linksToWork: "https://soundcloud.app.goo.gl/X94u2oBg7626c3bB8\n\nhttps://youtube.com/channel/UCm8utJlMuE9LFvnS3SWN1XQ",
    genre: "UK Garage, Grime",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "54",
    name: "Humzah Awan",
    artistName: "No Nation",
    contactDetails: "humzahawan@gmail.com",
    location: "Bristol",
    creativeDisciplines: "DJ, Producer",
    linksToWork: "http://thelivinglevel.tumblr.com",
    genre: "Jungle, dnb, rave",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "55",
    name: "Kiran Kotecha",
    artistName: "yourboykiran",
    contactDetails: "447748482474",
    location: "London",
    creativeDisciplines: "DJ / Producer",
    linksToWork: "link.bio/yourboykiran",
    genre: "Flips + Edits / Baile Funk / UK Funky / Breaks / UKG / 140 / Electro / 160 / Jungle",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "56",
    name: "Rahul Dhulipala",
    artistName: "DJ Solar Plexus",
    contactDetails: "@djsolarplexus on insta, 07827157867, rahul.dhulipala@gmail.com",
    location: "London / Swansea",
    creativeDisciplines: "DJ Solar Plexus",
    linksToWork: "https://soundcloud.app.goo.gl/J8mo82sSFSBYxEQ19",
    genre: "ukg, uk dubstep, jungle, 160, grime",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "57",
    name: "Sahil Dhingra",
    artistName: "Abana",
    contactDetails: "7507255056",
    location: "London // Los Angeles",
    creativeDisciplines: "Producer / DJ / Conceptor / Designer",
    linksToWork: "https://linktr.ee/abana",
    genre: "house / electro / electronic / UK (all genres)",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "58",
    name: "Puneet Gill",
    artistName: "Petit P",
    contactDetails: "7807538110",
    location: "London",
    creativeDisciplines: "DJ",
    linksToWork: "https://instagram.com/djpetitp?r=nametag\nhttps://m.soundcloud.com/djpetitp",
    genre: "House, techo, funk, disco",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "59",
    name: "Nayanika Chatterjee",
    artistName: "Nayanika Chatterjee",
    contactDetails: "",
    location: "Mumbai, India",
    creativeDisciplines: "Animator/Illustrator",
    linksToWork: "https://nayanikachatterjee.com",
    genre: "",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "60",
    name: "Samia",
    artistName: "Nadī",
    contactDetails: "7943344457",
    location: "London",
    creativeDisciplines: "DJ and Host and animation producer",
    linksToWork: "Soundcloud.com/thisisnadi",
    genre: "Club, dancehall, R&b, hiphop, Asian underground and more",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "61",
    name: "Nihal Kanwar",
    artistName: "TRAFFICC",
    contactDetails: "M: +91 9811871234, E: trafficcmusic@gmail.com, Insta: trafficccccc",
    location: "New Delhi, India",
    creativeDisciplines: "DJ, Producer, Graphic Designer, Video Editor.",
    linksToWork: "https://linktr.ee/trafficcmusic",
    genre: "Techno, House, Garage, Breaks, Bass",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "62",
    name: "Alvi Hussain",
    artistName: "Alvi Island",
    contactDetails: "alvihussain96@gmail.com +447943222485",
    location: "South London/Manchester",
    creativeDisciplines: "DJ/Producer",
    linksToWork: "https://soundcloud.com/alvi-island?utm_source=mobi&utm_campaign=social_sharing&utm_terms=hackedsounds.control\n\nhttps://youtube.com/channel/UCm8utJlMuE9LFvnS3SWN1XQ",
    genre: "Garage/Bass",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "63",
    name: "Tommy Khosla",
    artistName: "Tommy Khosla",
    contactDetails: "07548076526 - whatsapp and phone - tommykhosla@gmail.com - email - @tommykhosla - instagram -",
    location: "London. Also have family in Devon.",
    creativeDisciplines: "Music Artist - Sitarist",
    linksToWork: "https://linktr.ee/tommykhosla\n\nhttps://open.spotify.com/artist/299x8OrChLy2BDJVwQeNdX?si=vu5SjVwGQH2U5XDUxkdoWA\n\nhttps://www.instagram.com/tommykhosla/",
    genre: "Electro Indo-Jazz (or Neo Indo-Jazz - we're still working genre descriptors out!) Also, I usually perform with my band which is called Jawari",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "64",
    name: "Nicholas Subramaniam",
    artistName: "Cralias / DJ animebby",
    contactDetails: "7450296185",
    location: "London",
    creativeDisciplines: "DJ and photographer",
    linksToWork: "Cralias.bandcamp.com\nSoundCloud.com/cralias\nSoundCloud.com/djanimebby",
    genre: "Cralias - UK bass/grime/club track (120 -140 stuff. DJ animebby - jungle/cheeky remixes/Nightcore/donk / happy hardcore (160-180 stuff)",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "65",
    name: "manj virdee",
    artistName: "manj",
    contactDetails: "beatsbymanj@gmail.com",
    location: "Walsall",
    creativeDisciplines: "DJ",
    linksToWork: "soundcloud.com/beatsbymanj",
    genre: "ukg, jungle, breaks, house, dubstep",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "66",
    name: "Rouhangeze Baichoo",
    artistName: "Rouhangeze",
    contactDetails: "Rouhangeze1@gmail.com",
    location: "London",
    creativeDisciplines: "Singer, songwriter, composer, music producer, Radio Presenter, Curator",
    linksToWork: "https://youtube.com/c/Rouhangeze\nhttps://planetradio.co.uk/jazz-fm/shows/rouhangeze/\nWww.rouhangeze.com",
    genre: "Multi genre - have been involved with various genres of different genres throughout my career - Global, Jazz, Ethno Jazz, Pop, Vocals, Orchestral, Acoustic",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "67",
    name: "Kirat Aulakh",
    artistName: "KIRAT",
    contactDetails: "instagram: kirataul",
    location: "South west/ midlands",
    creativeDisciplines: "DJ",
    linksToWork: "soundcloud @kirataul",
    genre: "multi genre- mainly house, breaks, jungle, funky",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "68",
    name: "Nathan",
    artistName: "Eternal Rebel",
    contactDetails: "7946183423",
    location: "London",
    creativeDisciplines: "DJ, Artist",
    linksToWork: "https://youtu.be/RznfEz5279o\nhttps://www.mixcloud.com/bmcradio/eternal-rebel-w-coco-021222/\n(Soundcloud under construction)",
    genre: "Garage, House",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "69",
    name: "Anish Patel",
    artistName: "Twix",
    contactDetails: "7848853584",
    location: "Peterborough & London",
    creativeDisciplines: "Dj & promoter",
    linksToWork: "House.sessions on Instagram",
    genre: "House, tech, deep, minimal & disco.... Sprinkle of dub too",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "70",
    name: "Piyush Nigam",
    artistName: "Piyush Nigam",
    contactDetails: "",
    location: "London",
    creativeDisciplines: "DJ, Producer, Singer, Songwriter",
    linksToWork: "https://linktr.ee/piyushnigammusic",
    genre: "House, techno, south Asian, Bollywood, punjabi ( Bhangra)",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "71",
    name: "Timothy Ezekiel",
    artistName: "WVRM POOL",
    contactDetails: "alex.ezekiel.t@gmail.com",
    location: "London, UK",
    creativeDisciplines: "DJ, Visual Artist",
    linksToWork: "https://soundcloud.com/wvrmpool",
    genre: "Techno, Trance, Hard Groove, Breakbeat",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "72",
    name: "Anthony philip",
    artistName: "Kuta",
    contactDetails: "Anthonyphilipc@gmail.com",
    location: "Sydney, Australia",
    creativeDisciplines: "DJ",
    linksToWork: "https://on.soundcloud.com/H7cf2LbyYy1dqReAA\n\nhttps://on.soundcloud.com/9bbqF9pA5jyBRUxVA",
    genre: "Street-Soul, Dub and Reggae, Breaks, Prog tech and electro",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "73",
    name: "Anand Raghavan",
    artistName: "Mossambi",
    contactDetails: "Phone: 07449079830 Instagram: mossambianand",
    location: "London",
    creativeDisciplines: "DJ, Producer, do occasional visual projections for events",
    linksToWork: "My release on All Centre: https://mossambi.bandcamp.com/album/resurf\n\nAll other stuff is here, and some of my visuals work is on my Instagram, as well as details of events etc I've been part of:\nhttps://linktr.ee/mossambi",
    genre: "UK Techno, Bass, Dubstep, Experimental",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "74",
    name: "Kapil Vijh",
    artistName: "Caprice Sühñ",
    contactDetails: "kapilvijh@hotmail.co.uk; 07986544056 ; @capricesuhndj instagra,",
    location: "SW London",
    creativeDisciplines: "DJ",
    linksToWork: "https://www.mixcloud.com/capricesuhn/",
    genre: "Gay house, desi, 00s pop, electronica, Bollywood, rave, techno",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "75",
    name: "Maryam Jameela",
    artistName: "JAMEELA",
    contactDetails: "akajameela@gmail.com",
    location: "Leeds",
    creativeDisciplines: "DJ, Visual Artist",
    linksToWork: "https://soundcloud.com/akajameela",
    genre: "bass, garage, house, dubstep, breaks, 2step, funky, jungle, dnb, footwork",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "76",
    name: "Ki",
    artistName: "leverson",
    contactDetails: "07469932257 / ki@levrsn.com",
    location: "London",
    creativeDisciplines: "DJ",
    linksToWork: "levrsn.com/presskit",
    genre: "hip-hop, r&b, soul, jazz, future beats",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "77",
    name: "2NV",
    artistName: "2NV",
    contactDetails: "7510040038",
    location: "Birmingham",
    creativeDisciplines: "DJ/Artist",
    linksToWork: "https://on.soundcloud.com/8A6ShrsJQewXRb8N7",
    genre: "Garage/Panjabi/Bollywood/Hip-Hop/Trap",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "78",
    name: "Raj Chandrarajah",
    artistName: "Raj Chandra",
    contactDetails: "rajchandrarajah@outlook.com",
    location: "Glasgow",
    creativeDisciplines: "DJ",
    linksToWork: "https://on.soundcloud.com/NTAZcTMtZywBWn2H6",
    genre: "House, electronic, Italo",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "79",
    name: "Anthony philip",
    artistName: "kuta",
    contactDetails: "anthonyphilipc@gmail.com",
    location: "Australia",
    creativeDisciplines: "DJ",
    linksToWork: "https://on.soundcloud.com/Bwp7iEoET6t9s5Lp7\n\nhttps://on.soundcloud.com/eku4jeEa7WnUdtYj7\n\nhttps://on.soundcloud.com/rV7YRxg1897brR1H7\n\nhttps://on.soundcloud.com/yxqgHDnsnvyXtnk36\n\n\n\nShared lineups with: DJ SPEN, DJ ASSAULT, SOICHI Terada, AceMo, Klon Dump, Laurence Guy, Salute",
    genre: "Prog electro, 90's breakbeat, street-soul, dub / reggae",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "80",
    name: "Sarith Ratnayake",
    artistName: "Sarith",
    contactDetails: "7365234595",
    location: "London",
    creativeDisciplines: "DJ, Visual Artist, Designer",
    linksToWork: "https://linktr.ee/sarithhhh",
    genre: "House/ Electro/ Techno",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "81",
    name: "Yatharth Roy Vibhakar",
    artistName: "drēokt",
    contactDetails: "Email: drēokt@gmail.com",
    location: "Currently in India but moving to the UK in May/June.",
    creativeDisciplines: "Creative Director, Visual Designer, Music Composer, & Photographer.",
    linksToWork: "Instagram: https://instagram.com/dreokt/\nWebsite: www.dreokt.com\nLinktree: https://linktr.ee/dreokt",
    genre: "IDM, Experimental Electronica, Downtempo, Ambient, Soundtrack",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "82",
    name: "Chunz",
    artistName: "Chunz x Makh",
    contactDetails: "7980496648",
    location: "Leeds",
    creativeDisciplines: "DJ & MC",
    linksToWork: "https://on.soundcloud.com/N2GXFCADP3Ks4LUz5\n\nhttps://instagram.com/chunzxmakh?igshid=YmMyMTA2M2Y=",
    genre: "Funky , Garage and Desi Beats",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "83",
    name: "Akhilan Singam",
    artistName: "Gasing",
    contactDetails: "",
    location: "Bristol/Kuala Lumpur",
    creativeDisciplines: "DJ",
    linksToWork: "Check out GASING on #SoundCloud\nhttps://on.soundcloud.com/3wdWr",
    genre: "House, Techno, Garage, Breaks.",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "84",
    name: "Kansh",
    artistName: "XAETHERX",
    contactDetails: "6593210844",
    location: "Singapore",
    creativeDisciplines: "DJ, visual artist (abstract painting, illustration), event organiser, experimental Movement artist,",
    linksToWork: "https://linktr.ee/kanshh",
    genre: "hiphop rnb, footwork, jungle, bass, queer, experimental, indie alternative,",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "85",
    name: "Ral",
    artistName: "Rainmann",
    contactDetails: "rainmann@tuta.io / 07852229542",
    location: "White City, London",
    creativeDisciplines: "DJ/Producer",
    linksToWork: "https://rainmann.bandcamp.com/",
    genre: "House",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "86",
    name: "Bobby",
    artistName: "Papri Chaat",
    contactDetails: "bobby90mcmahon@gmail.com",
    location: "U.S. (Portland)",
    creativeDisciplines: "DJ",
    linksToWork: "soundcloud.com/paprichaat",
    genre: "left-field, electro, techno, house, club",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "87",
    name: "Dhanraj Mawani",
    artistName: "Shapeshifter",
    contactDetails: "dhanrajmavani@gmail.com",
    location: "Mumbai , India",
    creativeDisciplines: "Dj",
    linksToWork: "Listen to SHAPESHIFTER MIX 001 by shapeshifter.flac on #SoundCloud\nhttps://on.soundcloud.com/RNxpy",
    genre: "Electro , Asian Underground , Breakbeat",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "88",
    name: "Eshan Ashcroft",
    artistName: "Noakko",
    contactDetails: "Noakkoartist@gmail.com",
    location: "London!",
    creativeDisciplines: "Musician/producer/DJ",
    linksToWork: "https://open.spotify.com/album/3FHR0MoBqgSOiIRu7Qu1Ph?si=R2pREWTER72Q4VmS1fIwlg\n\nhttps://on.soundcloud.com/8YCvqU9WXKGDYMRt6\n\nhttps://on.soundcloud.com/VySQoGGMQv2of5EX8",
    genre: "Breaks, techno, ambient, electro",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "89",
    name: "Sarvesh Ramprakash",
    artistName: "Icarus Redux",
    contactDetails: "",
    location: "Washington, DC",
    creativeDisciplines: "DJ",
    linksToWork: "https://linktr.ee/IcarusRedux",
    genre: "open format",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "90",
    name: "Anvay",
    artistName: "axia / Chai Breaks",
    contactDetails: "chaibreaksmusic@gmail.com",
    location: "California",
    creativeDisciplines: "DJ / Photographer",
    linksToWork: "https://soundcloud.com/chai-breaks\nhttps://medium.com/@axia.images/hello-464396ef23e8",
    genre: "Electronic",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "91",
    name: "Kirat aulakh",
    artistName: "KIRAT",
    contactDetails: "Instagram: @kirataul",
    location: "South west + Leicester",
    creativeDisciplines: "DJ",
    linksToWork: "Soundcloud: https://on.soundcloud.com/8tpyNtTXZ9afaXUv9",
    genre: "House, jungle, breakbeat",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "92",
    name: "Channan Hanif",
    artistName: "Channan Hanif",
    contactDetails: "7534534461",
    location: "London",
    creativeDisciplines: "Producer, DJ, Vocalist, Actor, Writer, Illustrator",
    linksToWork: "https://www.instagram.com/channanhanif/?hl=en\n\nhttps://on.soundcloud.com/YGMSU",
    genre: "Techno, House, Electro, Disco, Electronica, Hip Hop",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "93",
    name: "Channan Hanif",
    artistName: "Channan Hanif",
    contactDetails: "7534534461",
    location: "London",
    creativeDisciplines: "Producer, DJ, Vocalist, Actor, Writer, Illustrator, Dancer",
    linksToWork: "https://instagram.com/channanhanif?igshid=YmMyMTA2M2Y=\n\nhttps://on.soundcloud.com/YGMSU\n\n",
    genre: "Techno, House, Electro-nica, Disco, Hip Hop",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "94",
    name: "Jenagan Sivakumar",
    artistName: "Cressida",
    contactDetails: "Jenagansivakumar@gmail.com",
    location: "Berlin",
    creativeDisciplines: "DJ",
    linksToWork: "Soundcloud.com/cressida",
    genre: "Bass, breaks, techno, electro",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "95",
    name: "Sharad Rao",
    artistName: "Easy Wanderlings",
    contactDetails: "7545888148",
    location: "London",
    creativeDisciplines: "Singer songwriter",
    linksToWork: "https://drive.google.com/file/d/1rwuNoioclJsWDKnzuXg6ws760KKyRcut/view?usp=drivesdk",
    genre: "Soul/ folk",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "96",
    name: "Aaditya Khurana",
    artistName: "Adi",
    contactDetails: "akhur303.ak@gmail.com / +447419142078 / @adi.khurana (instagram)",
    location: "Currently Berlin but I'm moving back to London in September",
    creativeDisciplines: "DJ",
    linksToWork: "https://soundcloud.com/4dikhurana/raggedyann-tics?si=c63ab4afce924b24887e3d368b02a70b&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing\n\n-\n\nhttps://soundcloud.com/4dikhurana/antics001?si=c98fae2efa444dc2aede99b84af6cfb3&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
    genre: "Tekno, Hardcore, Gabber, Jungle, Dubstep, Hyperpop, Bass,  (anything fun bouncy + bassy pretty much)",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "97",
    name: "Hassan Mallick",
    artistName: "NIRVANA PRINCIPLE",
    contactDetails: "07859373979 . The.nirvana.principle@gmail.com",
    location: "London",
    creativeDisciplines: "DJ/Producer/Podcaster",
    linksToWork: "Producer:\nhttps://open.spotify.com/track/0HIqOw2WAjJa0rEjG3Uaw2?si=kRHX4AzzQ--VZjzJDFT60g\n\nhttps://www.instagram.com/tv/CgQEaZHlf2T/?igshid=MmJiY2I4NDBkZg==\n\nPodcast/Radio:\nhttps://www.melodicdistraction.com/shows/nirvana-principle-show?id=49931\n\nDJ:\n\nhttps://on.soundcloud.com/fg5AmcHLFJMSGQUDA\n\n",
    genre: "World, electronica, Nu-Jazz , progressive and melodic house .",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "98",
    name: "Sijya Gupta",
    artistName: "Sijya",
    contactDetails: "919910021779",
    location: "New Delhi / London",
    creativeDisciplines: "Music Producer/Composer/Singer & Graphic Designer",
    linksToWork: "https://li.sten.to/sijya_younghate\nhttps://sijya.bandcamp.com",
    genre: "Electronic, Downtempo, Ambient, Art-Pop, Indie",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "99",
    name: "Hena Sharma",
    artistName: "Hena",
    contactDetails: "hena-sharma@hotmail.com / 07769275430",
    location: "London",
    creativeDisciplines: "Music Artist / Fashion Designer",
    linksToWork: "Music: https://open.spotify.com/artist/6EGh1ngCgfXWjmClmYHmYU?si=tlqL0qLqSG2HBQQQpkWYAA. Currently working on an EP and a bunch of new songs.\n\nThis is my fashion IG: https://www.instagram.com/rasa.ldn/",
    genre: "alternative/indie/r&b",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "100",
    name: "Usman Mahmood",
    artistName: "Ruuz",
    contactDetails: "7479680352",
    location: "London/ Dubai",
    creativeDisciplines: "DJ/ Promoter",
    linksToWork: "https://www.instagram.com/ruuzthedj/\nhttps://soundcloud.com/ruuz12",
    genre: "Urban, UKG, house, funky, Bassline, grime, desi, afro",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "101",
    name: "Harvey Shergill",
    artistName: "Izzet Garvey",
    contactDetails: "7415067064",
    location: "Leicester",
    creativeDisciplines: "DJ",
    linksToWork: "instagram.com/lowertone",
    genre: "UK CLUB, BREAKS",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "102",
    name: "Timothy Ezekiel",
    artistName: "WVRM POOL",
    contactDetails: "",
    location: "London, UK",
    creativeDisciplines: "DJ",
    linksToWork: "https://on.soundcloud.com/uspDs",
    genre: "Techno, Hard Groove, Trance",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "103",
    name: "zee shah",
    artistName: "zee",
    contactDetails: "7828336689",
    location: "Croydon",
    creativeDisciplines: "DJ",
    linksToWork: "https://www.mixcloud.com/z_double_e/i-eat-beats-for-breakfast/",
    genre: "grime, garage, jungle, house, indie-pop soul, bollywood, R&B",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "104",
    name: "Anjali Dhulipala",
    artistName: "DJ Anjchilli",
    contactDetails: "Phone no: 07983462500 Email:dhulipalaa@gmail.com",
    location: "London, UK",
    creativeDisciplines: "DJ",
    linksToWork: "https://on.soundcloud.com/XHQbrfZuQZ725Qbm6",
    genre: "UKG, Bollywood, Grime, Jungle, Baseline",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "105",
    name: "Saloni Boyina",
    artistName: "Saloni",
    contactDetails: "Email: saloni@salonimusic.com   Number: +447943529459",
    location: "Milton Keynes, UK",
    creativeDisciplines: "Artist",
    linksToWork: "Legacy (First Telugu/English Original) - http://www.salonimusic.com/legacy\n\nChali Mein (Women Empowerment Anthem) - http://www.salonimusic.com/chali-mein",
    genre: "Pop, R&B, Desi",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "106",
    name: "Juhi Gupta",
    artistName: "Lil Sur",
    contactDetails: "juhig01@gmail.com, +15109363437, @lilsurr",
    location: "San Francisco, CA",
    creativeDisciplines: "DJ, Graphic Designer",
    linksToWork: "juhi.design / https://soundcloud.com/littlesur",
    genre: "afro/latin/desi house, experimental club",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "107",
    name: "Ariel Remy Nurpuri",
    artistName: "The Bass Injector",
    contactDetails: "7757883615",
    location: "London",
    creativeDisciplines: "DJ, producer, promoter, label owner, A&R, video editor",
    linksToWork: "One of my tunes: https://on.soundcloud.com/FqYS6\n\nMy events brand (EST 2019) https://instagram.com/singularity.uk?igshid=MzNlNGNkZWQ4Mg==\n\nMy label (EST 2020)\nhttps://instagram.com/demolitionsquadron?igshid=OGQ5ZDc2ODk2ZA==\n\nMy experimental label (EST 2022)\nhttps://instagram.com/racket.recordings?igshid=OGQ5ZDc2ODk2ZA==\n\nMy darkside drum n bass label (EST 2022)\nhttps://instagram.com/notorioussteppaz?igshid=OGQ5ZDc2ODk2ZA==",
    genre: "The whole spectrum of the old skool UK sound",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "108",
    name: "Sasith Gamage",
    artistName: "IYRE",
    contactDetails: "iyrednb@gmail.com/leah@theboom.live",
    location: "Colombo/Sri Lanka - London/UK",
    creativeDisciplines: "Drum and Bass producer/DJ",
    linksToWork: "https://linktr.ee/IYREdnb",
    genre: "Drum and Bass",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "109",
    name: "Sattam Rahman",
    artistName: "Sattam",
    contactDetails: "7939686959",
    location: "London",
    creativeDisciplines: "DJ/Producer",
    linksToWork: "https://open.spotify.com/artist/6iyc6BGLOwF8ZZIfcaLVP7?si=moBFdQE8TAiTtD4SUivsfQ",
    genre: "House, garage, electro, trance",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "110",
    name: "Karan Ajmani",
    artistName: "Karan Ajmani",
    contactDetails: "",
    location: "Cambridge, UK",
    creativeDisciplines: "Music Producer / DJ",
    linksToWork: "Music Releases (On various labels incl. Deep Down, Future Avenue, Moofly, Bullfinch Records, etc)\n\nSpotify - \nhttps://open.spotify.com/artist/6bgAiG7HkofvuRsCAuDGy3?si=iemRzDgvRa-tgam_c8fUZg\n\nApple Music -  \nhttps://music.apple.com/us/artist/karan-ajmani/1439006010\n\nRecent Sets\n120-124 bpm Progressive House Set at Bloop London Radio - \nhttps://www.youtube.com/watch?v=i-BxDtkTFXQ&t=4398s&ab_channel=BloopLondonRadio\nOr \nhttps://soundcloud.com/blooplondon/circa-w-karan-140923?si=cf80fc95b2574318a826a39d87e0e48e&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing\n\n126-132 bpm Prog House / Melodic Techno Set at Transmission Cambridge - \nhttps://soundcloud.com/karanajmanii/beyong-the-horizon-04-transmission-05-may-2023?si=a3d3de9b26f2428fb2b490450951f63b&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing\n\n130-135 bpm Detroit Techno set at Found Sounds Cambridge - https://soundcloud.com/foundsoundscambridge/sets/found-sounds-17-03-23?si=b9936981381f42b6aca5ec1b43154104&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
    genre: "Progressive House, Melodic Techno, Dub Techno, Detroit Techno",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "111",
    name: "Satpal Singh",
    artistName: "Smoove Kriminal",
    contactDetails: "smoovekriminal@hotmail.co.uk",
    location: "London (East)",
    creativeDisciplines: "DJ / Producer / Radio Host",
    linksToWork: "https://linktr.ee/SmooveKriminal",
    genre: "UK Funky, Amapiano, UK Garage, House (Various), Jungle, Vinyl Sets, too!",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "112",
    name: "Safiya Bashir",
    artistName: "SAFIYA",
    contactDetails: "31648276247",
    location: "Amsterdam/Bristol",
    creativeDisciplines: "DJ",
    linksToWork: "https://soundcloud.com/safiya-bashir-273807362\nhttps://www.instagram.com/safiya.haneen/?hl=en",
    genre: "Bollywood, Afrodesi, Arab, Amapiano, UK Funky,  Garage.",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "113",
    name: "Jamaal  Johnson",
    artistName: "jjamz",
    contactDetails: "447426417967",
    location: "London (New York until mid Nov)",
    creativeDisciplines: "DJ",
    linksToWork: "https://linktr.ee/jjamz?fbclid=PAAabNxFGqYM6fQJ1bSkf4W6kn3WtN46TaKz8TPFpspgKRn6pTXtMNXTinCTY_aem_AY2d4EFvbY32-eVE5OXl0bVDoubbGpD_5H9mHdUsGwhXY6W4eVgSZBCpP_B9wPrP2gE",
    genre: "UK funky, Broken beat, Soulful House, Amapiano",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "114",
    name: "Abeera",
    artistName: "Abibi",
    contactDetails: "abibidoinmusic@gmail.com",
    location: "Berlin",
    creativeDisciplines: "DJ/Event organiser/Writer",
    linksToWork: "https://www.youtube.com/watch?v=CKW4bzn_mDU&ab_channel=KeepHush; https://refugeworldwide.com/radio/daytimers-abibi-21-jun-2023;\nhttps://www.youtube.com/results?search_query=abibi+hor+berlin;\nhttps://www.instagram.com/not.abibi/",
    genre: "Bass, experimental, UK, dance, traditional",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "115",
    name: "Vibhu Singh",
    artistName: "Kalbaisakhi",
    contactDetails: "447423665985",
    location: "London",
    creativeDisciplines: "Producer-DJ",
    linksToWork: "https://soundcloud.com/kalbaisakhimusic?utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing\n\nhttps://drive.google.com/file/d/15NmKKQie-4L2KDniZfwVAzyuKY_zBArF/view?usp=drive_link\n\nhttps://youtu.be/tO5I8yRk57I?si=U41-3M9GvAkatJsp\n\nhttps://youtu.be/Q_MbWLuNmIw?si=4cw3vPQsW4BhBGZR",
    genre: "House, Afrobeats, Amapiano, UK Funky, Baile Funk, Grime, Dubstep, Jungle, Hip-Hop",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "116",
    name: "Adnan",
    artistName: "adnan afghani",
    contactDetails: "adnany1198@gmail.com",
    location: "London",
    creativeDisciplines: "Sound Artist / DJ / Producer",
    linksToWork: "https://docs.google.com/document/d/1p0PTNNINo9n8J4LG_PKugKHVgw-O6nZO6svy0_wqzdc/edit?usp=sharing",
    genre: "Ambient / Glitch / Jungle / IDM / Ai",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "117",
    name: "Rohin",
    artistName: "Daskaran",
    contactDetails: "daskaran.music@gmail.com",
    location: "London",
    creativeDisciplines: "DJ/producer",
    linksToWork: "Listen to party girl anthems mix by ___Daskaran___ on #SoundCloud\nhttps://on.soundcloud.com/D6pxS\n\nhttps://on.soundcloud.com/mQrSY",
    genre: "Techno, trap",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "118",
    name: "Jay Ghelani",
    artistName: "JG:MC",
    contactDetails: "07903 393337",
    location: "Leicester",
    creativeDisciplines: "MC (Dnb, UKG + 140)",
    linksToWork: "https://soundcloud.com/efanuk/bigga-man-sound-feat-jgmc-demo-1/s-SQiju6JFXXT?ref=clipboard&p=i&c=1&si=3F9B4608764E4442BAA71F8FB1AE4E32&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing\n\nhttps://m.soundcloud.com/sakuraselections/mavros-jgmc-selecta?ref=clipboard&p=i&c=0&si=E0A237611BF24FAEA3EC86FD413CDB10&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing\n",
    genre: "Dnb & UKG",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "119",
    name: 'Hussain "Haseena" Abbas Zaidi',
    artistName: "Jaan-e-Haseena",
    contactDetails: "",
    location: "Lahore, Pakistan ; New York, NY",
    creativeDisciplines: "I am a DJ, Creative Director, Event Curator, Experimental Hip-Hop Producer, and Performer-Activist.",
    linksToWork: "Mix: https://soundcloud.com/jaanehaseena/premiere-infinity-records-the-modran-moorat\nSpotify: https://open.spotify.com/artist/1Cl9ZPPzWnEM7ockxRZuKh?si=d--xR_JXTxi-gMvXF6vLCw&nd=1&dlsi=0a493976c1294de0\nCreative Direction + Event Curation: https://www.instagram.com/zenaankhana/",
    genre: "Electro-Punk, Mujra/Femme-Pakistani Commerical/Classical, Hip-Hop",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "120",
    name: "zee shah",
    artistName: "early riser",
    contactDetails: "7961656786",
    location: "South East London",
    creativeDisciplines: "DJ",
    linksToWork: "N/A",
    genre: "Grime, Garage, House, Jungle, D&B, Electronica, Alternative, Bollywood,",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "121",
    name: "Shirin Naveed",
    artistName: "SHIR.IN",
    contactDetails: "",
    location: "South East London / Brum",
    creativeDisciplines: "DJ / Creative Producer and Visual Artist",
    linksToWork: "",
    genre: "140, dubstep, jungle, edits, breaks, baile, funky,",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "122",
    name: "NEO 10Y / Nikhil",
    artistName: "NEO 10Y",
    contactDetails: "neotenymusic@gmail.com // 07747896869",
    location: "London",
    creativeDisciplines: "Recording artist / multi disciplinary artist",
    linksToWork: "www.bio.site/neo10y // https://open.spotify.com/artist/3G1V2jfTZO61Hs3dX7ilrA?si=tgDW3irMQWW0kEwChTR1aQ",
    genre: "Genre expansive",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "123",
    name: "Hitesh Mistry",
    artistName: "Mistry",
    contactDetails: "7916100102",
    location: "London (North)",
    creativeDisciplines: "Singer songwriter & producer",
    linksToWork: "Check out Mistry's Socials & Music here:\nSpotify - https://open.spotify.com/artist/22EOuWI4bRUfaCfmEj04pt?si=H3V_JhNzS52iTIUCJP4Xeg \nInstagram - https://www.instagram.com/mistryofficial/\nYouTube - https://www.youtube.com/c/MistryOfficial \nTik Tok - https://www.tiktok.com/@mistryofficial_?lang=en \n\nSnippets of Mistry's previous performances:\nSpotify Birmingham Mela –  https://www.tiktok.com/@mistryofficial_/video/7260189531297549595?lang=en \nCardiff Mela -  https://www.youtube.com/shorts/ObsrGEaASdk",
    genre: "Alternative RnB",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "124",
    name: "Karum Cooper",
    artistName: "Webmoms / Karum Cooper",
    contactDetails: "7905774940",
    location: "Cornwall, UK",
    creativeDisciplines: "Music producer, songwriter, multi instrumentalist, poet and music artist",
    linksToWork: "https://open.spotify.com/artist/2ol5Xy14VMiqF9KjzW41c4",
    genre: "RnB, Neo Soul, Hip Hop, Rap, Lofi, jazzhop, instrumental beats",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "125",
    name: "Abid Rahman",
    artistName: "ABRZY",
    contactDetails: "abrzymusic@gmail.com",
    location: "London",
    creativeDisciplines: "Artist",
    linksToWork: "Here is my EPK, this has a great summary on me, my live performances, music videos and bios\n\nhttps://drive.google.com/file/d/1GfFfRifqniYyvcsRAhr8XhC-PY4kIYLE/view?usp=sharing\n\nThis is my Website- www.abrzy.com\n\nThese are my best songs on Spotify-\n\nAgua - https://open.spotify.com/track/2S2XZogeT4wjuGumb13zGL?si=ae93547b28ba4f57\n\nMidnight- https://open.spotify.com/track/73XNDrjd08WeL7nuqRC6pM?si=ee72da21d1994155\n\nSilly Flow - https://open.spotify.com/track/4VudjBzdMLX0zQ8FprzKkZ?si=a1d4b7b7ae9c4b4e\n\nAnd my Spotify Artist Page-  https://open.spotify.com/artist/0GIxnPuJrbOyBfyYkMzJRo?si=VugEPW_xTFOroj_TiH7rdw",
    genre: "Hip-Hop/Rap",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "126",
    name: "Ishani Jasmin",
    artistName: "Ishani Jasmin",
    contactDetails: "07954335688 / ishanijasmin@gmail.com",
    location: "London",
    creativeDisciplines: "Facilitator (music), musician, poet, writer, events organiser",
    linksToWork: "breakuphaircut.bandcamp.com\ngirlsrocklondon.com\ndecolonisefest.co.uk\ninstagram.com/firsttimersfest",
    genre: "punk, rock, alternative",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "127",
    name: "Raul Plahe",
    artistName: "Raul Made It",
    contactDetails: "7779944786",
    location: "London",
    creativeDisciplines: "Producer",
    linksToWork: "https://s.disco.ac/pppjscycentm",
    genre: "Pop, house, garage",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
  {
    id: "128",
    name: "Vidya Divakaran",
    artistName: "Vidya",
    contactDetails: "@vidyafunnies on Instagram, vidyadiva.1@gmail.com",
    location: "Ilford",
    creativeDisciplines: "Comedian and theatre maker, Event host and budding DJ - also a graphic designer",
    linksToWork: "https://www.instagram.com/vidyafunnies/",
    genre: "",
    timesBooked: 0,
    mostRecentEvent: "",
    mostRecentEventDate: "",
  },
];

export function searchDJs(query: string, djs: DJ[]): DJ[] {
  if (!query.trim()) return djs;
  
  const lowerQuery = query.toLowerCase();
  return djs.filter(
    (dj) =>
      dj.name.toLowerCase().includes(lowerQuery) ||
      dj.artistName.toLowerCase().includes(lowerQuery) ||
      dj.location.toLowerCase().includes(lowerQuery) ||
      dj.creativeDisciplines.toLowerCase().includes(lowerQuery) ||
      dj.genre.toLowerCase().includes(lowerQuery)
  );
}

export function addDJ(dj: Omit<DJ, "id">): DJ {
  const newDJ: DJ = {
    ...dj,
    id: Date.now().toString(),
  };
  return newDJ;
}
