export interface DJ {
  id: string;
  artistName: string;
  preferredName: string;
  preferredPronouns: string;
  heritage: string;
  location: string;
  outsideUK: string;
  typeOfAct: string;
  genre: string;
  contactDetails: string;
  instagram: string;
  soundcloud: string;
  tiktok: string;
  otherSocialMedia: string;
  linkToPreviousWork: string;
  mostRecentEventDate: string;
  mostRecentEvent: string;
  smallGigsCount: number;
  mediumGigsCount: number;
  largeGigsCount: number;
  gigScore: number;
}

export const dummyDJs: DJ[] = [
  {
    id: "1",
    artistName: "Zar",
    preferredName: "Arun Dhanjal",
    preferredPronouns: "he/him",
    heritage: "British Indian",
    location: "London",
    outsideUK: "Toured Europe 2023",
    typeOfAct: "DJ / Producer / Live performer",
    genre: "Multi genre",
    contactDetails: "adjzar@gmail.com",
    instagram: "https://instagram.com/ajdzar",
    soundcloud: "https://linktr.ee/ajdzar",
    tiktok: "@ajdzar",
    otherSocialMedia: "linktr.ee/ajdzar",
    linkToPreviousWork: "https://linktr.ee/ajdzar",
    mostRecentEvent: "Ministry of Sound",
    mostRecentEventDate: "Dec 2024",
    smallGigsCount: 18,
    mediumGigsCount: 3,
    largeGigsCount: 0,
    gigScore: 24,
  },
  {
    id: "2",
    artistName: "Saadaan",
    preferredName: "Saadaan Afghan",
    preferredPronouns: "he/him",
    heritage: "British Afghan",
    location: "Coventry / London",
    outsideUK: "Amsterdam, Berlin",
    typeOfAct: "DJ / Producer",
    genre: "140, Dubstep, Left Field Bass, 2-step/ukg, Hip Hop, Techno, Electro (sometimes House)",
    contactDetails: "saadaan@waveplate.systems",
    instagram: "https://instagram.com/saadaan_music",
    soundcloud: "saadaan.bandcamp.com",
    tiktok: "@saadaan_music",
    otherSocialMedia: "waveplate.systems",
    linkToPreviousWork: "saadaan.bandcamp.com\nwaveplate.systems",
    mostRecentEvent: "Night Tales",
    mostRecentEventDate: "Oct 2024",
    smallGigsCount: 16,
    mediumGigsCount: 9,
    largeGigsCount: 2,
    gigScore: 40,
  },
  {
    id: "3",
    artistName: "Michael Diamond",
    preferredName: "Michael Diamond",
    preferredPronouns: "",
    heritage: "",
    location: "Oxford/London",
    outsideUK: "",
    typeOfAct: "DJ / Producer / Live performer",
    genre: "Electronic, Jazz",
    contactDetails: "diamond.sounduk@gmail.com",
    instagram: "",
    soundcloud: "https://soundcloud.com/michaeldiamonduk",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.com/michaeldiamonduk",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 1,
    mediumGigsCount: 10,
    largeGigsCount: 2,
    gigScore: 27,
  },
  {
    id: "4",
    artistName: "Sita Shah",
    preferredName: "Sita Shah",
    preferredPronouns: "she/her",
    heritage: "British Gujarati",
    location: "London",
    outsideUK: "Sometimes NYC",
    typeOfAct: "DJ / Presenter / learning to produce",
    genre: "Techno, hardcore, breaks, desi, bootlegs",
    contactDetails: "sitashahsworld@gmail.com",
    instagram: "https://instagram.com/sitashahdj",
    soundcloud: "soundcloud.com/sitashahdj",
    tiktok: "@sitashahdj",
    otherSocialMedia: "Twitter: @sitashahsworld",
    linkToPreviousWork: "soundcloud.com/sitashahdj",
    mostRecentEvent: "Fold London",
    mostRecentEventDate: "Nov 2024",
    smallGigsCount: 9,
    mediumGigsCount: 4,
    largeGigsCount: 0,
    gigScore: 17,
  },
  {
    id: "5",
    artistName: "Rainmann",
    preferredName: "Ral Daryanani",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ / Producer / Live performer",
    genre: "All",
    contactDetails: "",
    instagram: "",
    soundcloud: "SoundCloud.com/rainm4nn",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "SoundCloud.com/rainm4nn",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 13,
    mediumGigsCount: 6,
    largeGigsCount: 2,
    gigScore: 31,
  },
  {
    id: "6",
    artistName: "Cardamami",
    preferredName: "Anisa Jackson",
    preferredPronouns: "she/her",
    heritage: "African American",
    location: "NYC",
    outsideUK: "NYC",
    typeOfAct: "DJ",
    genre: "All",
    contactDetails: "djcardamami@gmail.com",
    instagram: "https://instagram.com/djcardamami",
    soundcloud: "soundcloud.com/cardamami",
    tiktok: "@djcardamami",
    otherSocialMedia: "Bandcamp: cardamami.bandcamp.com",
    linkToPreviousWork: "soundcloud.com/cardamami",
    mostRecentEvent: "Brooklyn Mirage",
    mostRecentEventDate: "Sep 2024",
    smallGigsCount: 14,
    mediumGigsCount: 2,
    largeGigsCount: 0,
    gigScore: 18,
  },
  {
    id: "7",
    artistName: "GoodMostlyBad",
    preferredName: "Mehar Bedi",
    preferredPronouns: "",
    heritage: "",
    location: "Doha",
    outsideUK: "Doha",
    typeOfAct: "DJ / Producer",
    genre: "ASS CLAPS ONLY (Hiphop,Afrobeats, Amapiano,UKG,Bass,Dancehall,Trap etc)",
    contactDetails: "mehar.bedi@gmail.com",
    instagram: "",
    soundcloud: "soundcloud.com/goodmostlybad",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "soundcloud.com/goodmostlybad",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 10,
    mediumGigsCount: 3,
    largeGigsCount: 4,
    gigScore: 28,
  },
  {
    id: "8",
    artistName: "Somatic",
    preferredName: "Somin Griffin-Dave",
    preferredPronouns: "",
    heritage: "",
    location: "Exeter (Sometimes Bristol) but owns a car and is willing to travel.",
    outsideUK: "",
    typeOfAct: "DJ, Producer, Sound Designer, Sound Engineer.",
    genre: "DnB, Jungle, Breakbeat, Garage, IDM, Experimental, Various other 4x4 genres, (Classic) Afrobeat, a touch of bossa and various other things.",
    contactDetails: "somin.somatic@gmail.com",
    instagram: "",
    soundcloud: "linktr.ee/somin_somatic",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "linktr.ee/somin_somatic",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 8,
    mediumGigsCount: 4,
    largeGigsCount: 4,
    gigScore: 28,
  },
  {
    id: "9",
    artistName: "Liyo (new project called RISE coming soon)",
    preferredName: "Josh de Silva",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "Techno, Dubstep, Jungle, Garage, Electro etc etc",
    contactDetails: "",
    instagram: "",
    soundcloud: "https://soundcloud.com/liyomusic",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.com/liyomusic",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 17,
    mediumGigsCount: 7,
    largeGigsCount: 2,
    gigScore: 37,
  },
  {
    id: "10",
    artistName: "Freshta",
    preferredName: "Freshta Ebrahim",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ and Radio Host",
    genre: "Grime, Dubstep, Leftfield Bass, Breaks, Hard Drum",
    contactDetails: "freshtainfo@gmail.com",
    instagram: "",
    soundcloud: "linktr.ee/_freshta",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "linktr.ee/_freshta",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 14,
    mediumGigsCount: 1,
    largeGigsCount: 4,
    gigScore: 28,
  },
  {
    id: "11",
    artistName: "GoldTooth",
    preferredName: "Jaedan Gowthaman",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ, Producer",
    genre: "Grime, Dubstep, UK Funky, Garage, Drill, SA House, afrohouse, kuduro\n\nAlso specialise in vinyl sets",
    contactDetails: "dj@goldtooth.uk",
    instagram: "",
    soundcloud: "SoundCloud.com/goldtooth_dj",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "SoundCloud.com/goldtooth_dj",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 20,
    mediumGigsCount: 10,
    largeGigsCount: 0,
    gigScore: 40,
  },
  {
    id: "12",
    artistName: "Temujin",
    preferredName: "Roop",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ + Radio (producer soon come)",
    genre: "UK underground dance - Bass, Techno, Breaks, Garage, Jungle, Dubstep, Grime (heavy on the percs and dub)",
    contactDetails: "temujin.ldn@gmail.com",
    instagram: "",
    soundcloud: "soundcloud.com/temujin-ldn",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "soundcloud.com/temujin-ldn",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 15,
    mediumGigsCount: 7,
    largeGigsCount: 4,
    gigScore: 41,
  },
  {
    id: "13",
    artistName: "Darama",
    preferredName: "Dhillon Chhabra",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ, producer",
    genre: "UK Bass, anything percussive, Grime, Drill, House,Techno, UK Funky, UKG, Disco",
    contactDetails: "darama@daytimers.org",
    instagram: "",
    soundcloud: "https://soundcloud.com/daramadj",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.com/daramadj",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 15,
    mediumGigsCount: 4,
    largeGigsCount: 2,
    gigScore: 29,
  },
  {
    id: "14",
    artistName: "Saachi",
    preferredName: "Saachi",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "House (sometimes electro & Ghettotech)",
    contactDetails: "djsaachi@hotmail.com",
    instagram: "",
    soundcloud: "https://soundcloud.com/saachi-bains",
    tiktok: "",
    otherSocialMedia: "https://www.mixcloud.com/baachisains/",
    linkToPreviousWork: "https://www.mixcloud.com/baachisains/\n\nhttps://soundcloud.com/saachi-bains",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 11,
    mediumGigsCount: 3,
    largeGigsCount: 4,
    gigScore: 29,
  },
  {
    id: "15",
    artistName: "Kishan",
    preferredName: "Kishan Thakrar",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ & Producer",
    genre: "UKG, House, Hip Hop/Afrobeat, 140, Jungle, DnB etc",
    contactDetails: "music@kishan.co.uk",
    instagram: "",
    soundcloud: "https://soundcloud.com/kishanthakrar",
    tiktok: "",
    otherSocialMedia: "https://www.liinks.co/kishan",
    linkToPreviousWork: "https://www.liinks.co/kishan\n\nhttps://soundcloud.com/kishanthakrar",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 0,
    mediumGigsCount: 4,
    largeGigsCount: 4,
    gigScore: 20,
  },
  {
    id: "16",
    artistName: "DJ PRIYA",
    preferredName: "Priya Majhail",
    preferredPronouns: "",
    heritage: "",
    location: "London/ Brighton",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "Reggaeton, Bashment, Dancehall, Funky",
    contactDetails: "majpri95@gmail.com",
    instagram: "",
    soundcloud: "https://soundcloud.com/deejaypriya",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.com/deejaypriya",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 13,
    mediumGigsCount: 7,
    largeGigsCount: 2,
    gigScore: 33,
  },
  {
    id: "17",
    artistName: "Qwirk",
    preferredName: "Simaran Patel",
    preferredPronouns: "",
    heritage: "",
    location: "Manchester",
    outsideUK: "",
    typeOfAct: "DJ/Producer",
    genre: "Dubstep, Grime, Garage, Breakbeat, DnB, Footwork, Trap, Jungle",
    contactDetails: "qwirkdubstep@gmail.com",
    instagram: "",
    soundcloud: "https://soundcloud.com/qwirkk",
    tiktok: "",
    otherSocialMedia: "linktr.ee/qwirk",
    linkToPreviousWork: "linktr.ee/qwirk\n\nhttps://soundcloud.com/qwirkk",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 2,
    mediumGigsCount: 6,
    largeGigsCount: 0,
    gigScore: 14,
  },
  {
    id: "18",
    artistName: "Rohan Rakhit",
    preferredName: "Rohan Rakhit",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ/Presenter/Broadcaster",
    genre: "Multi-genre",
    contactDetails: "rohan@daytimers.org",
    instagram: "",
    soundcloud: "https://www.mixcloud.com/rohan-rakhit/",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://www.mixcloud.com/rohan-rakhit/",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 3,
    mediumGigsCount: 5,
    largeGigsCount: 0,
    gigScore: 13,
  },
  {
    id: "19",
    artistName: "Jaskkkkkkk",
    preferredName: "Jaskaran Notta",
    preferredPronouns: "",
    heritage: "",
    location: "Birmingham",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "Electro, Ghetto, Italo, breakbeat, chugg (sometimes garage, disco)",
    contactDetails: "jaskaran.notta97@gmail.com",
    instagram: "",
    soundcloud: "https://soundcloud.app.goo.gl/QLnxd5BZitZF8YHx7",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.app.goo.gl/QLnxd5BZitZF8YHx7",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 20,
    mediumGigsCount: 5,
    largeGigsCount: 2,
    gigScore: 36,
  },
  {
    id: "20",
    artistName: "Ash Lovecraft",
    preferredName: "Kashif Majeed",
    preferredPronouns: "",
    heritage: "",
    location: "Toronto",
    outsideUK: "Toronto",
    typeOfAct: "DJ/Producer",
    genre: "Moombahton/Dancehall",
    contactDetails: "ashlovecraftmusic@gmail.com",
    instagram: "",
    soundcloud: "HTTPS://www.soundcloud.com/ashlovecraft",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "HTTPS://www.soundcloud.com/ashlovecraft",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 2,
    mediumGigsCount: 3,
    largeGigsCount: 0,
    gigScore: 8,
  },
  {
    id: "21",
    artistName: "Adnan.Afghani",
    preferredName: "Adnan",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ/producer/\nfield recorder",
    genre: "140/160 (techno/breaks/idm/dubstep)\n+experimental",
    contactDetails: "",
    instagram: "",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "@adnan1198 | Linktree",
    linkToPreviousWork: "@adnan1198 | Linktree",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 8,
    mediumGigsCount: 7,
    largeGigsCount: 0,
    gigScore: 22,
  },
  {
    id: "22",
    artistName: "King Monday",
    preferredName: "Sherwyn Appadu",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ / Producer / Live performer",
    genre: "Turkish Psychedelic Folk\nExperimental",
    contactDetails: "kxmonday@hotmail.com",
    instagram: "",
    soundcloud: "https://soundcloud.com/kingxmonday",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.com/kingxmonday",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 0,
    mediumGigsCount: 7,
    largeGigsCount: 2,
    gigScore: 20,
  },
  {
    id: "23",
    artistName: "Antariksh Daddy/\nAarAv",
    preferredName: "Anandit Sachdev (Antariksh Records)",
    preferredPronouns: "",
    heritage: "",
    location: "Delhi",
    outsideUK: "Delhi",
    typeOfAct: "DJ/ Producer",
    genre: "Electronic (Everything 110 to 160 BMP)\n\nVinyl only sets too.",
    contactDetails: "contact@ananditsachdev.com",
    instagram: "",
    soundcloud: "https://soundcloud.com/anandit-sachdev",
    tiktok: "",
    otherSocialMedia: "https://soundcloud.com/antarikshrecs",
    linkToPreviousWork: "https://soundcloud.com/antarikshrecs (LABEL)\n\nhttps://soundcloud.com/anandit-sachdev (PERSONAL)",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 13,
    mediumGigsCount: 10,
    largeGigsCount: 0,
    gigScore: 33,
  },
  {
    id: "24",
    artistName: "Mandle",
    preferredName: "Debesh Mandal",
    preferredPronouns: "",
    heritage: "",
    location: "London / Manchester",
    outsideUK: "",
    typeOfAct: "DJ/Producer/Presenter",
    genre: "House, Techno, Breaks, Jungle, Disco",
    contactDetails: "mandle.demain@gmail.com",
    instagram: "",
    soundcloud: "https://soundcloud.com/djmandle",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.com/djmandle",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 18,
    mediumGigsCount: 0,
    largeGigsCount: 2,
    gigScore: 24,
  },
  {
    id: "25",
    artistName: "REA",
    preferredName: "Rea Chawhan",
    preferredPronouns: "",
    heritage: "",
    location: "Bristol/London/Madrid",
    outsideUK: "",
    typeOfAct: "DJ/Producer",
    genre: "Dnb, Breaks/Footwork, UKG, UK Dubstep",
    contactDetails: "",
    instagram: "",
    soundcloud: "https://soundcloud.com/readnb",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.com/readnb",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 10,
    mediumGigsCount: 10,
    largeGigsCount: 0,
    gigScore: 30,
  },
  {
    id: "26",
    artistName: "Sepoys",
    preferredName: "Rohit Tandon",
    preferredPronouns: "",
    heritage: "",
    location: "Vancouver, BC",
    outsideUK: "Vancouver, BC",
    typeOfAct: "DJ/Producer",
    genre: "Liquid DnB/ Jungle",
    contactDetails: "basspradesh@gmail.com",
    instagram: "",
    soundcloud: "https://soundcloud.com/sepoys",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.com/sepoys",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 15,
    mediumGigsCount: 0,
    largeGigsCount: 4,
    gigScore: 27,
  },
  {
    id: "27",
    artistName: "Provhat",
    preferredName: "Provhat Rahman",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ/Producer",
    genre: "UK Bass",
    contactDetails: "provhat@daytimers.org",
    instagram: "",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "-",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 19,
    mediumGigsCount: 2,
    largeGigsCount: 2,
    gigScore: 29,
  },
  {
    id: "28",
    artistName: "Mera Bhai",
    preferredName: "Kavhan Karthik",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ/Producer/Multi-instrumentalist/Radio Host",
    genre: "Detroit + Italo House + Disco,  Acid House, Techno, Breaks, Funk, UKG, Global Riddims. Vinyl only sets include - strictly UKG, 70s-80s Bollywood disco, world/int'l psych/funk/disco",
    contactDetails: "merabhaiiimusic@gmail.com",
    instagram: "",
    soundcloud: "https://linktr.ee/merabhaiii",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://linktr.ee/merabhaiii",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 2,
    mediumGigsCount: 8,
    largeGigsCount: 2,
    gigScore: 24,
  },
  {
    id: "29",
    artistName: "Izzi",
    preferredName: "Izzi Dickson",
    preferredPronouns: "",
    heritage: "",
    location: "Cambridge/London (student)",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "UK bass, breaks, leftfield techno, hard drum, electro, jungle, footwork",
    contactDetails: "phone: 07517223023",
    instagram: "",
    soundcloud: "https://soundcloud.app.goo.gl/aXWw6FdyUhNKSXZi6",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "Mixes/radio: https://soundcloud.app.goo.gl/aXWw6FdyUhNKSXZi6",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 14,
    mediumGigsCount: 4,
    largeGigsCount: 0,
    gigScore: 22,
  },
  {
    id: "30",
    artistName: "Sita Shah",
    preferredName: "Sita Shah",
    preferredPronouns: "",
    heritage: "",
    location: "London / New York",
    outsideUK: "New York",
    typeOfAct: "DJ, Aspiring Producer, Director, Conceptual Creative",
    genre: "Techno, edits, desi ... Anything fast and fun!",
    contactDetails: "7506229329",
    instagram: "",
    soundcloud: "https://soundcloud.com/sitashahdj",
    tiktok: "",
    otherSocialMedia: "https://www.sitashahcreative.com/",
    linkToPreviousWork: "https://soundcloud.com/sitashahdj\nhttps://www.sitashahcreative.com/",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 14,
    mediumGigsCount: 5,
    largeGigsCount: 0,
    gigScore: 24,
  },
  {
    id: "31",
    artistName: "Sunayah",
    preferredName: "Sunayah Arshad",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "Producer (shoots + events), writer, sometimes DJ",
    genre: "",
    contactDetails: "sunayah.arshad@gmail.com",
    instagram: "",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "www.sunayah.co.uk",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 10,
    mediumGigsCount: 10,
    largeGigsCount: 0,
    gigScore: 30,
  },
  {
    id: "32",
    artistName: "Triqi",
    preferredName: "Iqra Nowshari",
    preferredPronouns: "",
    heritage: "",
    location: "Berlin, Germany",
    outsideUK: "Berlin, Germany",
    typeOfAct: "DJ",
    genre: "house, breaks, electro, techno, disco, soul, funk",
    contactDetails: "",
    instagram: "",
    soundcloud: "www.soundcloud.com/triqi030",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "www.soundcloud.com/triqi030",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 9,
    mediumGigsCount: 4,
    largeGigsCount: 2,
    gigScore: 23,
  },
  {
    id: "33",
    artistName: "REA",
    preferredName: "rea chawhan",
    preferredPronouns: "",
    heritage: "",
    location: "bristol",
    outsideUK: "",
    typeOfAct: "dj/producer",
    genre: "ukg, drum and bass, breakbeat/footwork, dubstep",
    contactDetails: "reamusickuk@gmail.com or +447402944409",
    instagram: "",
    soundcloud: "https://soundcloud.com/reamusicuk",
    tiktok: "",
    otherSocialMedia: "https://open.spotify.com/artist/1nhQOYji5l5jrGliSvMvc6?si=7hnX6-8fTJmcG_eLjG-qbQ",
    linkToPreviousWork: "https://soundcloud.com/reamusicuk, \n\nhttps://open.spotify.com/artist/1nhQOYji5l5jrGliSvMvc6?si=7hnX6-8fTJmcG_eLjG-qbQ",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 7,
    mediumGigsCount: 3,
    largeGigsCount: 0,
    gigScore: 13,
  },
  {
    id: "34",
    artistName: "KRMA",
    preferredName: "Kush Varma",
    preferredPronouns: "",
    heritage: "",
    location: "LA",
    outsideUK: "LA",
    typeOfAct: "Producer, DJ",
    genre: "Electronic, trap, dnb, bass",
    contactDetails: "email - krmabeats@gmail.com",
    instagram: "",
    soundcloud: "https://linktr.ee/krma.music",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://linktr.ee/krma.music",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 11,
    mediumGigsCount: 10,
    largeGigsCount: 0,
    gigScore: 31,
  },
  {
    id: "35",
    artistName: "Solar Plexus",
    preferredName: "Rahul Dhulipala",
    preferredPronouns: "",
    heritage: "",
    location: "London / South Wales",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "ukg / uk dubstep / grime / breaks / 160 / jungle",
    contactDetails: "7827157867",
    instagram: "",
    soundcloud: "https://soundcloud.app.goo.gl/i44Mavo4fsdjnxzf8",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.app.goo.gl/i44Mavo4fsdjnxzf8",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 13,
    mediumGigsCount: 6,
    largeGigsCount: 2,
    gigScore: 31,
  },
  {
    id: "36",
    artistName: "Basra",
    preferredName: "Harry Basra",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "",
    contactDetails: "Harrybasra1@gmail.com",
    instagram: "",
    soundcloud: "https://soundcloud.app.goo.gl/Yvtor8jbtP9kxs1w8",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.app.goo.gl/Yvtor8jbtP9kxs1w8",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 10,
    mediumGigsCount: 9,
    largeGigsCount: 4,
    gigScore: 40,
  },
  {
    id: "37",
    artistName: "G33",
    preferredName: "Gaia Ahuja",
    preferredPronouns: "she/her",
    heritage: "British Asian",
    location: "Liverpool / London",
    outsideUK: "Toured India 2024",
    typeOfAct: "DJ / presenter",
    genre: "UKG, UK funky, grime, bass, dancehall",
    contactDetails: "gaiaahuja7@hotmail.com // 07845752577",
    instagram: "https://www.instagram.com/gaia_ia/",
    soundcloud: "https://soundcloud.com/gggeethreethree/bbc-asian-network-pure-spice-guest-mix",
    tiktok: "@gaia_ia",
    otherSocialMedia: "YouTube: gggeethreethree",
    linkToPreviousWork: "https://www.youtube.com/watch?v=iFqQZTupAqY https://www.instagram.com/p/CaU3bIGKTyR/\nhttps://www.youtube.com/watch?v=GSFsI7SXQ9k\nhttps://soundcloud.com/gggeethreethree/bbc-asian-network-pure-spice-guest-mix",
    mostRecentEvent: "BBC Asian Network Pure Spice",
    mostRecentEventDate: "Jan 2024",
    smallGigsCount: 6,
    mediumGigsCount: 9,
    largeGigsCount: 4,
    gigScore: 36,
  },
  {
    id: "38",
    artistName: "Himay",
    preferredName: "Himay",
    preferredPronouns: "",
    heritage: "",
    location: "Mumbai",
    outsideUK: "Mumbai",
    typeOfAct: "Dj, producer, graphic designer",
    genre: "House",
    contactDetails: "Himay.kumbhani89@gmail.com",
    instagram: "",
    soundcloud: "https://linktr.ee/heeemay",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://linktr.ee/heeemay",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 4,
    mediumGigsCount: 0,
    largeGigsCount: 0,
    gigScore: 4,
  },
  {
    id: "39",
    artistName: "Shortsell",
    preferredName: "Apoorv Khanna",
    preferredPronouns: "",
    heritage: "",
    location: "India",
    outsideUK: "India",
    typeOfAct: "DJ",
    genre: "Genre agnostic",
    contactDetails: "",
    instagram: "",
    soundcloud: "https://linktr.ee/shortsell",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://linktr.ee/shortsell",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 8,
    mediumGigsCount: 3,
    largeGigsCount: 0,
    gigScore: 14,
  },
  {
    id: "40",
    artistName: "IYRE",
    preferredName: "Sasith Gamage",
    preferredPronouns: "",
    heritage: "",
    location: "Colombo, Sri Lanka",
    outsideUK: "Colombo, Sri Lanka",
    typeOfAct: "Producer/DJ",
    genre: "Drum and Bass",
    contactDetails: "94716558996",
    instagram: "",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://youtu.be/xVYnI8jOShE\nhttps://youtu.be/ma0nEs2GU08\nhttps://youtu.be/uxJDLwxyePE\nhttps://youtu.be/jrmmYabx04s\nhttps://youtu.be/57P7vSPuh0c\nhttps://youtu.be/m6AQcVeCYWM\nhttps://ukf.com/words/iyre-is-proudly-putting-sri-lanka-on-the-drum-bass-map/31353\nhttps://ukf.com/news/ukf-future-vision-artists-revealed/32438\nhttps://mixmag.asia/read/iyre-sri-lanka-global-drumnbass-new-releases\nhttps://mixmag.asia/read/iyre-liquid-drumnbass-mixmag-asia-radio-sri-lanka-exclusive-mixes",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 8,
    mediumGigsCount: 7,
    largeGigsCount: 0,
    gigScore: 22,
  },
  {
    id: "41",
    artistName: "Jayhaan",
    preferredName: "Jehan Bhesania",
    preferredPronouns: "",
    heritage: "",
    location: "Mumbai, India",
    outsideUK: "Mumbai, India",
    typeOfAct: "Dj / Producer",
    genre: "Asian Underground / Open Format",
    contactDetails: "",
    instagram: "",
    soundcloud: "ghelo.biglink.to/jayhaan",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "ghelo.biglink.to/jayhaan",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 3,
    mediumGigsCount: 9,
    largeGigsCount: 0,
    gigScore: 21,
  },
  {
    id: "42",
    artistName: "Iti",
    preferredName: "Itrat (Iti) Memon",
    preferredPronouns: "",
    heritage: "",
    location: "Brisbane, Australia (for now)",
    outsideUK: "Brisbane, Australia",
    typeOfAct: "DJ, Producer, Live Electronic Performer, Label Director, Manager",
    genre: "UK Funky, Breaks, Electro, Garage, 2-step, ambient",
    contactDetails: "iti@affix.management",
    instagram: "",
    soundcloud: "https://iti-mqn.bandcamp.com/album/curvework-vol-1-as-time-passes",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://iti-mqn.bandcamp.com/album/curvework-vol-1-as-time-passes",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 1,
    mediumGigsCount: 3,
    largeGigsCount: 4,
    gigScore: 19,
  },
  {
    id: "43",
    artistName: "Snad",
    preferredName: "Shyam Anand",
    preferredPronouns: "",
    heritage: "",
    location: "Philadelphia/Berlin",
    outsideUK: "Philadelphia/Berlin",
    typeOfAct: "DJ/Producer",
    genre: "house, garage (New York, New Jersey and UK), good tech house",
    contactDetails: "",
    instagram: "",
    soundcloud: "soundcloud.com/snad",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "soundcloud.com/snad",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 6,
    mediumGigsCount: 6,
    largeGigsCount: 2,
    gigScore: 24,
  },
  {
    id: "44",
    artistName: "Gasing",
    preferredName: "Akhilan Singam",
    preferredPronouns: "",
    heritage: "",
    location: "Kuala Lumpur (Moving to Bristol in August)",
    outsideUK: "Kuala Lumpur",
    typeOfAct: "DJ",
    genre: "House, Techno, Garage, Grime, Jungle",
    contactDetails: "IG: gasingraised // Tel: +60122969596 // Email: akhilan2512@gmail.com",
    instagram: "gasingraised",
    soundcloud: "https://soundcloud.com/gasingraised",
    tiktok: "",
    otherSocialMedia: "https://www.mixcloud.com/gasingraised/",
    linkToPreviousWork: "https://www.mixcloud.com/gasingraised/\nhttps://soundcloud.com/gasingraised",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 17,
    mediumGigsCount: 9,
    largeGigsCount: 0,
    gigScore: 35,
  },
  {
    id: "45",
    artistName: "Kai Kaspar",
    preferredName: "Raj Chandrarajah",
    preferredPronouns: "",
    heritage: "",
    location: "Glasgow",
    outsideUK: "",
    typeOfAct: "DJ/Producer",
    genre: "House, electro & acid",
    contactDetails: "7827225208",
    instagram: "",
    soundcloud: "https://soundcloud.app.goo.gl/cCSTTNREucHxqDXy9",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.app.goo.gl/cCSTTNREucHxqDXy9",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 1,
    mediumGigsCount: 9,
    largeGigsCount: 0,
    gigScore: 19,
  },
  {
    id: "46",
    artistName: "Full Motion Disaster",
    preferredName: "Aniket Dabholkar",
    preferredPronouns: "",
    heritage: "",
    location: "Mumbai, India",
    outsideUK: "Mumbai, India",
    typeOfAct: "DJ, Producer, Label Owner (Filth Inc.)",
    genre: "Ghettotech, Breaks, Electro, House, Hard Dance",
    contactDetails: "fullmotiondisaster@gmail.com",
    instagram: "",
    soundcloud: "https://soundcloud.com/filth-inc-official/full-motion-disaster-x-dm-90-no-respite",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.com/filth-inc-official/full-motion-disaster-x-dm-90-no-respite",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 1,
    mediumGigsCount: 2,
    largeGigsCount: 4,
    gigScore: 17,
  },
  {
    id: "47",
    artistName: "Dushume",
    preferredName: "Dr Amit Dinesh Patel",
    preferredPronouns: "",
    heritage: "",
    location: "Leicester",
    outsideUK: "",
    typeOfAct: "Noise/ Experimental Sound Artist / DJ",
    genre: "Noise, Experimental Sound, Glitch, Electroacoustic music, Sound Art, Live Electronics",
    contactDetails: "7790064378",
    instagram: "",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "www.dushume.co.uk",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 7,
    mediumGigsCount: 0,
    largeGigsCount: 0,
    gigScore: 7,
  },
  {
    id: "48",
    artistName: "Ghosty",
    preferredName: "Nik Sahdev",
    preferredPronouns: "",
    heritage: "",
    location: "Liverpool",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "Jungle, DnB",
    contactDetails: "Dnbghosty@gmail.com",
    instagram: "Www.Instagram.com/Nik.ghosty",
    soundcloud: "https://soundcloud.app.goo.gl/jvRkYtRdQbaamWh8A",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.app.goo.gl/jvRkYtRdQbaamWh8A",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 8,
    mediumGigsCount: 8,
    largeGigsCount: 4,
    gigScore: 36,
  },
  {
    id: "49",
    artistName: "ORDERLY ROOM",
    preferredName: "Dani Wijesinghe",
    preferredPronouns: "",
    heritage: "",
    location: "Bristol, UK",
    outsideUK: "",
    typeOfAct: "DJ, writer",
    genre: "bass music, deconstructed club, hard drum, techno, noise, industril",
    contactDetails: "wijesinghedani@gmail.com / 07999845101",
    instagram: "",
    soundcloud: "soundcloud.com/orderly-room",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "soundcloud.com/orderly-room",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 12,
    mediumGigsCount: 9,
    largeGigsCount: 2,
    gigScore: 36,
  },
  {
    id: "50",
    artistName: "JAY TAPES",
    preferredName: "Vijay Patel",
    preferredPronouns: "",
    heritage: "",
    location: "Wapping, London",
    outsideUK: "",
    typeOfAct: "DJ / Amateur Producer",
    genre: "House, Techno, Electro, Breaks, Dubstep, Footwork, Reggaeton /Baile, Jungle, etc",
    contactDetails: "7939000149",
    instagram: "",
    soundcloud: "soundcloud.com/jaytapes",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "soundcloud.com/jaytapes",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 2,
    mediumGigsCount: 3,
    largeGigsCount: 4,
    gigScore: 20,
  },
  {
    id: "51",
    artistName: "élan vital",
    preferredName: "Pranam Mavahalli",
    preferredPronouns: "",
    heritage: "",
    location: "Manchester",
    outsideUK: "",
    typeOfAct: "Musician/producer/DJ",
    genre: "Breaks/electronic/jungle/beats",
    contactDetails: "elanvitalbeats@gmail.com",
    instagram: "",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "https://open.spotify.com/artist/6PVOJqMGjo0XqIRuc3v1vs?si=gE1xPku1TUqkGhunC4NKhg",
    linkToPreviousWork: "https://open.spotify.com/artist/6PVOJqMGjo0XqIRuc3v1vs?si=gE1xPku1TUqkGhunC4NKhg",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 10,
    mediumGigsCount: 5,
    largeGigsCount: 4,
    gigScore: 32,
  },
  {
    id: "52",
    artistName: "OT",
    preferredName: "Omer Tariq",
    preferredPronouns: "",
    heritage: "",
    location: "Bedford",
    outsideUK: "",
    typeOfAct: "Vinyl DJ",
    genre: "Indian classical music",
    contactDetails: "7940164390",
    instagram: "",
    soundcloud: "https://m.mixcloud.com/ot/",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://m.mixcloud.com/ot/",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 3,
    mediumGigsCount: 2,
    largeGigsCount: 0,
    gigScore: 7,
  },
  {
    id: "53",
    artistName: "Alvi Island",
    preferredName: "Alvi",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "Producer/DJ",
    genre: "UK Garage, Grime",
    contactDetails: "7943222485",
    instagram: "",
    soundcloud: "https://soundcloud.app.goo.gl/X94u2oBg7626c3bB8",
    tiktok: "",
    otherSocialMedia: "https://youtube.com/channel/UCm8utJlMuE9LFvnS3SWN1XQ",
    linkToPreviousWork: "https://soundcloud.app.goo.gl/X94u2oBg7626c3bB8\n\nhttps://youtube.com/channel/UCm8utJlMuE9LFvnS3SWN1XQ",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 16,
    mediumGigsCount: 8,
    largeGigsCount: 2,
    gigScore: 38,
  },
  {
    id: "54",
    artistName: "No Nation",
    preferredName: "Humzah Awan",
    preferredPronouns: "",
    heritage: "",
    location: "Bristol",
    outsideUK: "",
    typeOfAct: "DJ, Producer",
    genre: "Jungle, dnb, rave",
    contactDetails: "humzahawan@gmail.com",
    instagram: "",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "http://thelivinglevel.tumblr.com",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 0,
    mediumGigsCount: 6,
    largeGigsCount: 4,
    gigScore: 24,
  },
  {
    id: "55",
    artistName: "yourboykiran",
    preferredName: "Kiran Kotecha",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ / Producer",
    genre: "Flips + Edits / Baile Funk / UK Funky / Breaks / UKG / 140 / Electro / 160 / Jungle",
    contactDetails: "447748482474",
    instagram: "",
    soundcloud: "link.bio/yourboykiran",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "link.bio/yourboykiran",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 9,
    mediumGigsCount: 6,
    largeGigsCount: 4,
    gigScore: 33,
  },
  {
    id: "56",
    artistName: "DJ Solar Plexus",
    preferredName: "Rahul Dhulipala",
    preferredPronouns: "",
    heritage: "",
    location: "London / Swansea",
    outsideUK: "",
    typeOfAct: "DJ Solar Plexus",
    genre: "ukg, uk dubstep, jungle, 160, grime",
    contactDetails: "@djsolarplexus on insta, 07827157867, rahul.dhulipala@gmail.com",
    instagram: "@djsolarplexus",
    soundcloud: "https://soundcloud.app.goo.gl/J8mo82sSFSBYxEQ19",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.app.goo.gl/J8mo82sSFSBYxEQ19",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 4,
    mediumGigsCount: 2,
    largeGigsCount: 2,
    gigScore: 14,
  },
  {
    id: "57",
    artistName: "Abana",
    preferredName: "Sahil Dhingra",
    preferredPronouns: "",
    heritage: "",
    location: "London // Los Angeles",
    outsideUK: "Los Angeles",
    typeOfAct: "Producer / DJ / Conceptor / Designer",
    genre: "house / electro / electronic / UK (all genres)",
    contactDetails: "7507255056",
    instagram: "",
    soundcloud: "https://linktr.ee/abana",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://linktr.ee/abana",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 10,
    mediumGigsCount: 3,
    largeGigsCount: 4,
    gigScore: 28,
  },
  {
    id: "58",
    artistName: "Petit P",
    preferredName: "Puneet Gill",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "House, techo, funk, disco",
    contactDetails: "7807538110",
    instagram: "https://instagram.com/djpetitp?r=nametag",
    soundcloud: "https://m.soundcloud.com/djpetitp",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://instagram.com/djpetitp?r=nametag\nhttps://m.soundcloud.com/djpetitp",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 6,
    mediumGigsCount: 1,
    largeGigsCount: 2,
    gigScore: 14,
  },
  {
    id: "59",
    artistName: "Nayanika Chatterjee",
    preferredName: "Nayanika Chatterjee",
    preferredPronouns: "",
    heritage: "",
    location: "Mumbai, India",
    outsideUK: "Mumbai, India",
    typeOfAct: "Animator/Illustrator",
    genre: "",
    contactDetails: "",
    instagram: "",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://nayanikachatterjee.com",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 11,
    mediumGigsCount: 2,
    largeGigsCount: 0,
    gigScore: 15,
  },
  {
    id: "60",
    artistName: "Nadī",
    preferredName: "Samia",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ and Host and animation producer",
    genre: "Club, dancehall, R&b, hiphop, Asian underground and more",
    contactDetails: "7943344457",
    instagram: "",
    soundcloud: "Soundcloud.com/thisisnadi",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "Soundcloud.com/thisisnadi",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 7,
    mediumGigsCount: 0,
    largeGigsCount: 0,
    gigScore: 7,
  },
  {
    id: "61",
    artistName: "TRAFFICC",
    preferredName: "Nihal Kanwar",
    preferredPronouns: "",
    heritage: "",
    location: "New Delhi, India",
    outsideUK: "New Delhi, India",
    typeOfAct: "DJ, Producer, Graphic Designer, Video Editor.",
    genre: "Techno, House, Garage, Breaks, Bass",
    contactDetails: "M: +91 9811871234, E: trafficcmusic@gmail.com, Insta: trafficccccc",
    instagram: "trafficccccc",
    soundcloud: "https://linktr.ee/trafficcmusic",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://linktr.ee/trafficcmusic",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 7,
    mediumGigsCount: 9,
    largeGigsCount: 0,
    gigScore: 25,
  },
  {
    id: "62",
    artistName: "Alvi Island",
    preferredName: "Alvi Hussain",
    preferredPronouns: "",
    heritage: "",
    location: "South London/Manchester",
    outsideUK: "",
    typeOfAct: "DJ/Producer",
    genre: "Garage/Bass",
    contactDetails: "alvihussain96@gmail.com +447943222485",
    instagram: "",
    soundcloud: "https://soundcloud.com/alvi-island",
    tiktok: "",
    otherSocialMedia: "https://youtube.com/channel/UCm8utJlMuE9LFvnS3SWN1XQ",
    linkToPreviousWork: "https://soundcloud.com/alvi-island\n\nhttps://youtube.com/channel/UCm8utJlMuE9LFvnS3SWN1XQ",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 13,
    mediumGigsCount: 8,
    largeGigsCount: 2,
    gigScore: 35,
  },
  {
    id: "63",
    artistName: "Tommy Khosla",
    preferredName: "Tommy Khosla",
    preferredPronouns: "",
    heritage: "",
    location: "London. Also have family in Devon.",
    outsideUK: "",
    typeOfAct: "Music Artist - Sitarist",
    genre: "Electro Indo-Jazz (or Neo Indo-Jazz - we're still working genre descriptors out!) Also, I usually perform with my band which is called Jawari",
    contactDetails: "07548076526 - tommykhosla@gmail.com",
    instagram: "https://www.instagram.com/tommykhosla/",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "https://open.spotify.com/artist/299x8OrChLy2BDJVwQeNdX?si=vu5SjVwGQH2U5XDUxkdoWA",
    linkToPreviousWork: "https://linktr.ee/tommykhosla\n\nhttps://open.spotify.com/artist/299x8OrChLy2BDJVwQeNdX?si=vu5SjVwGQH2U5XDUxkdoWA\n\nhttps://www.instagram.com/tommykhosla/",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 7,
    mediumGigsCount: 0,
    largeGigsCount: 0,
    gigScore: 7,
  },
  {
    id: "64",
    artistName: "Cralias / DJ animebby",
    preferredName: "Nicholas Subramaniam",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ and photographer",
    genre: "Cralias - UK bass/grime/club track (120 -140 stuff. DJ animebby - jungle/cheeky remixes/Nightcore/donk / happy hardcore (160-180 stuff)",
    contactDetails: "7450296185",
    instagram: "",
    soundcloud: "SoundCloud.com/cralias",
    tiktok: "",
    otherSocialMedia: "Cralias.bandcamp.com",
    linkToPreviousWork: "Cralias.bandcamp.com\nSoundCloud.com/cralias\nSoundCloud.com/djanimebby",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 8,
    mediumGigsCount: 4,
    largeGigsCount: 0,
    gigScore: 16,
  },
  {
    id: "65",
    artistName: "manj",
    preferredName: "manj virdee",
    preferredPronouns: "",
    heritage: "",
    location: "Walsall",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "ukg, jungle, breaks, house, dubstep",
    contactDetails: "beatsbymanj@gmail.com",
    instagram: "",
    soundcloud: "soundcloud.com/beatsbymanj",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "soundcloud.com/beatsbymanj",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 11,
    mediumGigsCount: 3,
    largeGigsCount: 4,
    gigScore: 29,
  },
  {
    id: "66",
    artistName: "Rouhangeze",
    preferredName: "Rouhangeze Baichoo",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "Singer, songwriter, composer, music producer, Radio Presenter, Curator",
    genre: "Multi genre - have been involved with various genres of different genres throughout my career - Global, Jazz, Ethno Jazz, Pop, Vocals, Orchestral, Acoustic",
    contactDetails: "Rouhangeze1@gmail.com",
    instagram: "",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "https://youtube.com/c/Rouhangeze\nhttps://planetradio.co.uk/jazz-fm/shows/rouhangeze/\nWww.rouhangeze.com",
    linkToPreviousWork: "https://youtube.com/c/Rouhangeze\nhttps://planetradio.co.uk/jazz-fm/shows/rouhangeze/\nWww.rouhangeze.com",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 14,
    mediumGigsCount: 6,
    largeGigsCount: 4,
    gigScore: 38,
  },
  {
    id: "67",
    artistName: "KIRAT",
    preferredName: "Kirat Aulakh",
    preferredPronouns: "",
    heritage: "",
    location: "South west/ midlands",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "multi genre- mainly house, breaks, jungle, funky",
    contactDetails: "instagram: kirataul",
    instagram: "kirataul",
    soundcloud: "soundcloud @kirataul",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "soundcloud @kirataul",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 5,
    mediumGigsCount: 9,
    largeGigsCount: 0,
    gigScore: 23,
  },
  {
    id: "68",
    artistName: "Eternal Rebel",
    preferredName: "Nathan",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ, Artist",
    genre: "Garage, House",
    contactDetails: "7946183423",
    instagram: "",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "https://www.mixcloud.com/bmcradio/eternal-rebel-w-coco-021222/",
    linkToPreviousWork: "https://youtu.be/RznfEz5279o\nhttps://www.mixcloud.com/bmcradio/eternal-rebel-w-coco-021222/\n(Soundcloud under construction)",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 13,
    mediumGigsCount: 4,
    largeGigsCount: 0,
    gigScore: 21,
  },
  {
    id: "69",
    artistName: "Twix",
    preferredName: "Anish Patel",
    preferredPronouns: "",
    heritage: "",
    location: "Peterborough & London",
    outsideUK: "",
    typeOfAct: "Dj & promoter",
    genre: "House, tech, deep, minimal & disco.... Sprinkle of dub too",
    contactDetails: "7848853584",
    instagram: "House.sessions",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "House.sessions on Instagram",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 1,
    mediumGigsCount: 6,
    largeGigsCount: 0,
    gigScore: 13,
  },
  {
    id: "70",
    artistName: "Piyush Nigam",
    preferredName: "Piyush Nigam",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ, Producer, Singer, Songwriter",
    genre: "House, techno, south Asian, Bollywood, punjabi ( Bhangra)",
    contactDetails: "",
    instagram: "",
    soundcloud: "https://linktr.ee/piyushnigammusic",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://linktr.ee/piyushnigammusic",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 8,
    mediumGigsCount: 7,
    largeGigsCount: 0,
    gigScore: 22,
  },
  {
    id: "71",
    artistName: "WVRM POOL",
    preferredName: "Timothy Ezekiel",
    preferredPronouns: "",
    heritage: "",
    location: "London, UK",
    outsideUK: "",
    typeOfAct: "DJ, Visual Artist",
    genre: "Techno, Trance, Hard Groove, Breakbeat",
    contactDetails: "alex.ezekiel.t@gmail.com",
    instagram: "",
    soundcloud: "https://soundcloud.com/wvrmpool",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.com/wvrmpool",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 12,
    mediumGigsCount: 6,
    largeGigsCount: 4,
    gigScore: 36,
  },
  {
    id: "72",
    artistName: "Kuta",
    preferredName: "Anthony philip",
    preferredPronouns: "",
    heritage: "",
    location: "Sydney, Australia",
    outsideUK: "Sydney, Australia",
    typeOfAct: "DJ",
    genre: "Street-Soul, Dub and Reggae, Breaks, Prog tech and electro",
    contactDetails: "Anthonyphilipc@gmail.com",
    instagram: "",
    soundcloud: "https://on.soundcloud.com/H7cf2LbyYy1dqReAA",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://on.soundcloud.com/H7cf2LbyYy1dqReAA\n\nhttps://on.soundcloud.com/9bbqF9pA5jyBRUxVA",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 12,
    mediumGigsCount: 8,
    largeGigsCount: 4,
    gigScore: 40,
  },
  {
    id: "73",
    artistName: "Mossambi",
    preferredName: "Anand Raghavan",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ, Producer, do occasional visual projections for events",
    genre: "UK Techno, Bass, Dubstep, Experimental",
    contactDetails: "Phone: 07449079830 Instagram: mossambianand",
    instagram: "mossambianand",
    soundcloud: "https://mossambi.bandcamp.com/album/resurf",
    tiktok: "",
    otherSocialMedia: "https://linktr.ee/mossambi",
    linkToPreviousWork: "https://mossambi.bandcamp.com/album/resurf\n\nhttps://linktr.ee/mossambi",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 20,
    mediumGigsCount: 3,
    largeGigsCount: 0,
    gigScore: 26,
  },
  {
    id: "74",
    artistName: "Caprice Sühñ",
    preferredName: "Kapil Vijh",
    preferredPronouns: "",
    heritage: "",
    location: "SW London",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "Gay house, desi, 00s pop, electronica, Bollywood, rave, techno",
    contactDetails: "kapilvijh@hotmail.co.uk; 07986544056",
    instagram: "@capricesuhndj",
    soundcloud: "https://www.mixcloud.com/capricesuhn/",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://www.mixcloud.com/capricesuhn/",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 12,
    mediumGigsCount: 10,
    largeGigsCount: 4,
    gigScore: 44,
  },
  {
    id: "75",
    artistName: "JAMEELA",
    preferredName: "Maryam Jameela",
    preferredPronouns: "",
    heritage: "",
    location: "Leeds",
    outsideUK: "",
    typeOfAct: "DJ, Visual Artist",
    genre: "bass, garage, house, dubstep, breaks, 2step, funky, jungle, dnb, footwork",
    contactDetails: "akajameela@gmail.com",
    instagram: "",
    soundcloud: "https://soundcloud.com/akajameela",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.com/akajameela",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 5,
    mediumGigsCount: 6,
    largeGigsCount: 2,
    gigScore: 23,
  },
  {
    id: "76",
    artistName: "leverson",
    preferredName: "Ki",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "hip-hop, r&b, soul, jazz, future beats",
    contactDetails: "07469932257 / ki@levrsn.com",
    instagram: "",
    soundcloud: "levrsn.com/presskit",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "levrsn.com/presskit",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 0,
    mediumGigsCount: 6,
    largeGigsCount: 0,
    gigScore: 12,
  },
  {
    id: "77",
    artistName: "2NV",
    preferredName: "2NV",
    preferredPronouns: "",
    heritage: "",
    location: "Birmingham",
    outsideUK: "",
    typeOfAct: "DJ/Artist",
    genre: "Garage/Panjabi/Bollywood/Hip-Hop/Trap",
    contactDetails: "7510040038",
    instagram: "",
    soundcloud: "https://on.soundcloud.com/8A6ShrsJQewXRb8N7",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://on.soundcloud.com/8A6ShrsJQewXRb8N7",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 16,
    mediumGigsCount: 1,
    largeGigsCount: 0,
    gigScore: 18,
  },
  {
    id: "78",
    artistName: "Raj Chandra",
    preferredName: "Raj Chandrarajah",
    preferredPronouns: "",
    heritage: "",
    location: "Glasgow",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "House, electronic, Italo",
    contactDetails: "rajchandrarajah@outlook.com",
    instagram: "",
    soundcloud: "https://on.soundcloud.com/NTAZcTMtZywBWn2H6",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://on.soundcloud.com/NTAZcTMtZywBWn2H6",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 18,
    mediumGigsCount: 0,
    largeGigsCount: 4,
    gigScore: 30,
  },
  {
    id: "79",
    artistName: "kuta",
    preferredName: "Anthony philip",
    preferredPronouns: "",
    heritage: "",
    location: "Australia",
    outsideUK: "Australia",
    typeOfAct: "DJ",
    genre: "Prog electro, 90's breakbeat, street-soul, dub / reggae",
    contactDetails: "anthonyphilipc@gmail.com",
    instagram: "",
    soundcloud: "https://on.soundcloud.com/Bwp7iEoET6t9s5Lp7",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://on.soundcloud.com/Bwp7iEoET6t9s5Lp7\n\nhttps://on.soundcloud.com/eku4jeEa7WnUdtYj7\n\nhttps://on.soundcloud.com/rV7YRxg1897brR1H7\n\nhttps://on.soundcloud.com/yxqgHDnsnvyXtnk36\n\nShared lineups with: DJ SPEN, DJ ASSAULT, SOICHI Terada, AceMo, Klon Dump, Laurence Guy, Salute",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 1,
    mediumGigsCount: 10,
    largeGigsCount: 2,
    gigScore: 27,
  },
  {
    id: "80",
    artistName: "Sarith",
    preferredName: "Sarith Ratnayake",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ, Visual Artist, Designer",
    genre: "House/ Electro/ Techno",
    contactDetails: "7365234595",
    instagram: "",
    soundcloud: "https://linktr.ee/sarithhhh",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://linktr.ee/sarithhhh",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 4,
    mediumGigsCount: 8,
    largeGigsCount: 2,
    gigScore: 26,
  },
  {
    id: "81",
    artistName: "drēokt",
    preferredName: "Yatharth Roy Vibhakar",
    preferredPronouns: "",
    heritage: "",
    location: "Currently in India but moving to the UK in May/June.",
    outsideUK: "India",
    typeOfAct: "Creative Director, Visual Designer, Music Composer, & Photographer.",
    genre: "IDM, Experimental Electronica, Downtempo, Ambient, Soundtrack",
    contactDetails: "Email: drēokt@gmail.com",
    instagram: "https://instagram.com/dreokt/",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "https://linktr.ee/dreokt",
    linkToPreviousWork: "Instagram: https://instagram.com/dreokt/\nWebsite: www.dreokt.com\nLinktree: https://linktr.ee/dreokt",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 4,
    mediumGigsCount: 4,
    largeGigsCount: 0,
    gigScore: 12,
  },
  {
    id: "82",
    artistName: "Chunz x Makh",
    preferredName: "Chunz",
    preferredPronouns: "",
    heritage: "",
    location: "Leeds",
    outsideUK: "",
    typeOfAct: "DJ & MC",
    genre: "Funky , Garage and Desi Beats",
    contactDetails: "7980496648",
    instagram: "https://instagram.com/chunzxmakh",
    soundcloud: "https://on.soundcloud.com/N2GXFCADP3Ks4LUz5",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://on.soundcloud.com/N2GXFCADP3Ks4LUz5\n\nhttps://instagram.com/chunzxmakh",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 11,
    mediumGigsCount: 5,
    largeGigsCount: 2,
    gigScore: 27,
  },
  {
    id: "83",
    artistName: "Gasing",
    preferredName: "Akhilan Singam",
    preferredPronouns: "",
    heritage: "",
    location: "Bristol/Kuala Lumpur",
    outsideUK: "Kuala Lumpur",
    typeOfAct: "DJ",
    genre: "House, Techno, Garage, Breaks.",
    contactDetails: "",
    instagram: "",
    soundcloud: "https://on.soundcloud.com/3wdWr",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://on.soundcloud.com/3wdWr",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 11,
    mediumGigsCount: 10,
    largeGigsCount: 0,
    gigScore: 31,
  },
  {
    id: "84",
    artistName: "XAETHERX",
    preferredName: "Kansh",
    preferredPronouns: "",
    heritage: "",
    location: "Singapore",
    outsideUK: "Singapore",
    typeOfAct: "DJ, visual artist (abstract painting, illustration), event organiser, experimental Movement artist,",
    genre: "hiphop rnb, footwork, jungle, bass, queer, experimental, indie alternative,",
    contactDetails: "6593210844",
    instagram: "",
    soundcloud: "https://linktr.ee/kanshh",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://linktr.ee/kanshh",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 2,
    mediumGigsCount: 0,
    largeGigsCount: 2,
    gigScore: 8,
  },
  {
    id: "85",
    artistName: "Rainmann",
    preferredName: "Ral",
    preferredPronouns: "",
    heritage: "",
    location: "White City, London",
    outsideUK: "",
    typeOfAct: "DJ/Producer",
    genre: "House",
    contactDetails: "rainmann@tuta.io / 07852229542",
    instagram: "",
    soundcloud: "https://rainmann.bandcamp.com/",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://rainmann.bandcamp.com/",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 4,
    mediumGigsCount: 7,
    largeGigsCount: 4,
    gigScore: 30,
  },
  {
    id: "86",
    artistName: "Papri Chaat",
    preferredName: "Bobby",
    preferredPronouns: "",
    heritage: "",
    location: "U.S. (Portland)",
    outsideUK: "U.S. (Portland)",
    typeOfAct: "DJ",
    genre: "left-field, electro, techno, house, club",
    contactDetails: "bobby90mcmahon@gmail.com",
    instagram: "",
    soundcloud: "soundcloud.com/paprichaat",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "soundcloud.com/paprichaat",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 7,
    mediumGigsCount: 8,
    largeGigsCount: 2,
    gigScore: 29,
  },
  {
    id: "87",
    artistName: "Shapeshifter",
    preferredName: "Dhanraj Mawani",
    preferredPronouns: "",
    heritage: "",
    location: "Mumbai , India",
    outsideUK: "Mumbai, India",
    typeOfAct: "Dj",
    genre: "Electro , Asian Underground , Breakbeat",
    contactDetails: "dhanrajmavani@gmail.com",
    instagram: "",
    soundcloud: "https://on.soundcloud.com/RNxpy",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://on.soundcloud.com/RNxpy",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 18,
    mediumGigsCount: 4,
    largeGigsCount: 0,
    gigScore: 26,
  },
  {
    id: "88",
    artistName: "Noakko",
    preferredName: "Eshan Ashcroft",
    preferredPronouns: "",
    heritage: "",
    location: "London!",
    outsideUK: "",
    typeOfAct: "Musician/producer/DJ",
    genre: "Breaks, techno, ambient, electro",
    contactDetails: "Noakkoartist@gmail.com",
    instagram: "",
    soundcloud: "https://on.soundcloud.com/8YCvqU9WXKGDYMRt6",
    tiktok: "",
    otherSocialMedia: "https://open.spotify.com/album/3FHR0MoBqgSOiIRu7Qu1Ph?si=R2pREWTER72Q4VmS1fIwlg",
    linkToPreviousWork: "https://open.spotify.com/album/3FHR0MoBqgSOiIRu7Qu1Ph?si=R2pREWTER72Q4VmS1fIwlg\n\nhttps://on.soundcloud.com/8YCvqU9WXKGDYMRt6\n\nhttps://on.soundcloud.com/VySQoGGMQv2of5EX8",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 6,
    mediumGigsCount: 3,
    largeGigsCount: 4,
    gigScore: 24,
  },
  {
    id: "89",
    artistName: "Icarus Redux",
    preferredName: "Sarvesh Ramprakash",
    preferredPronouns: "",
    heritage: "",
    location: "Washington, DC",
    outsideUK: "Washington, DC",
    typeOfAct: "DJ",
    genre: "open format",
    contactDetails: "",
    instagram: "",
    soundcloud: "https://linktr.ee/IcarusRedux",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://linktr.ee/IcarusRedux",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 12,
    mediumGigsCount: 4,
    largeGigsCount: 4,
    gigScore: 32,
  },
  {
    id: "90",
    artistName: "axia / Chai Breaks",
    preferredName: "Anvay",
    preferredPronouns: "",
    heritage: "",
    location: "California",
    outsideUK: "California",
    typeOfAct: "DJ / Photographer",
    genre: "Electronic",
    contactDetails: "chaibreaksmusic@gmail.com",
    instagram: "",
    soundcloud: "https://soundcloud.com/chai-breaks",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.com/chai-breaks\nhttps://medium.com/@axia.images/hello-464396ef23e8",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 17,
    mediumGigsCount: 4,
    largeGigsCount: 0,
    gigScore: 25,
  },
  {
    id: "91",
    artistName: "KIRAT",
    preferredName: "Kirat aulakh",
    preferredPronouns: "",
    heritage: "",
    location: "South west + Leicester",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "House, jungle, breakbeat",
    contactDetails: "Instagram: @kirataul",
    instagram: "@kirataul",
    soundcloud: "https://on.soundcloud.com/8tpyNtTXZ9afaXUv9",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://on.soundcloud.com/8tpyNtTXZ9afaXUv9",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 2,
    mediumGigsCount: 4,
    largeGigsCount: 0,
    gigScore: 10,
  },
  {
    id: "92",
    artistName: "Channan Hanif",
    preferredName: "Channan Hanif",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "Producer, DJ, Vocalist, Actor, Writer, Illustrator",
    genre: "Techno, House, Electro, Disco, Electronica, Hip Hop",
    contactDetails: "7534534461",
    instagram: "https://www.instagram.com/channanhanif/?hl=en",
    soundcloud: "https://on.soundcloud.com/YGMSU",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://www.instagram.com/channanhanif/?hl=en\n\nhttps://on.soundcloud.com/YGMSU",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 3,
    mediumGigsCount: 4,
    largeGigsCount: 4,
    gigScore: 23,
  },
  {
    id: "93",
    artistName: "Channan Hanif",
    preferredName: "Channan Hanif",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "Producer, DJ, Vocalist, Actor, Writer, Illustrator, Dancer",
    genre: "Techno, House, Electro-nica, Disco, Hip Hop",
    contactDetails: "7534534461",
    instagram: "https://instagram.com/channanhanif",
    soundcloud: "https://on.soundcloud.com/YGMSU",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://instagram.com/channanhanif\n\nhttps://on.soundcloud.com/YGMSU",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 4,
    mediumGigsCount: 6,
    largeGigsCount: 0,
    gigScore: 16,
  },
  {
    id: "94",
    artistName: "Cressida",
    preferredName: "Jenagan Sivakumar",
    preferredPronouns: "",
    heritage: "",
    location: "Berlin",
    outsideUK: "Berlin",
    typeOfAct: "DJ",
    genre: "Bass, breaks, techno, electro",
    contactDetails: "Jenagansivakumar@gmail.com",
    instagram: "",
    soundcloud: "Soundcloud.com/cressida",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "Soundcloud.com/cressida",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 14,
    mediumGigsCount: 10,
    largeGigsCount: 4,
    gigScore: 46,
  },
  {
    id: "95",
    artistName: "Easy Wanderlings",
    preferredName: "Sharad Rao",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "Singer songwriter",
    genre: "Soul/ folk",
    contactDetails: "7545888148",
    instagram: "",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://drive.google.com/file/d/1rwuNoioclJsWDKnzuXg6ws760KKyRcut/view?usp=drivesdk",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 6,
    mediumGigsCount: 8,
    largeGigsCount: 0,
    gigScore: 22,
  },
  {
    id: "96",
    artistName: "Adi",
    preferredName: "Aaditya Khurana",
    preferredPronouns: "",
    heritage: "",
    location: "Currently Berlin but I'm moving back to London in September",
    outsideUK: "Berlin",
    typeOfAct: "DJ",
    genre: "Tekno, Hardcore, Gabber, Jungle, Dubstep, Hyperpop, Bass,  (anything fun bouncy + bassy pretty much)",
    contactDetails: "akhur303.ak@gmail.com / +447419142078",
    instagram: "@adi.khurana",
    soundcloud: "https://soundcloud.com/4dikhurana/raggedyann-tics",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.com/4dikhurana/raggedyann-tics\n\nhttps://soundcloud.com/4dikhurana/antics001",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 10,
    mediumGigsCount: 0,
    largeGigsCount: 0,
    gigScore: 10,
  },
  {
    id: "97",
    artistName: "NIRVANA PRINCIPLE",
    preferredName: "Hassan Mallick",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ/Producer/Podcaster",
    genre: "World, electronica, Nu-Jazz , progressive and melodic house .",
    contactDetails: "07859373979 . The.nirvana.principle@gmail.com",
    instagram: "",
    soundcloud: "https://on.soundcloud.com/fg5AmcHLFJMSGQUDA",
    tiktok: "",
    otherSocialMedia: "https://www.melodicdistraction.com/shows/nirvana-principle-show?id=49931",
    linkToPreviousWork: "https://open.spotify.com/track/0HIqOw2WAjJa0rEjG3Uaw2?si=kRHX4AzzQ--VZjzJDFT60g\n\nhttps://on.soundcloud.com/fg5AmcHLFJMSGQUDA",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 4,
    mediumGigsCount: 5,
    largeGigsCount: 4,
    gigScore: 26,
  },
  {
    id: "98",
    artistName: "Sijya",
    preferredName: "Sijya Gupta",
    preferredPronouns: "",
    heritage: "",
    location: "New Delhi / London",
    outsideUK: "New Delhi",
    typeOfAct: "Music Producer/Composer/Singer & Graphic Designer",
    genre: "Electronic, Downtempo, Ambient, Art-Pop, Indie",
    contactDetails: "919910021779",
    instagram: "",
    soundcloud: "https://sijya.bandcamp.com",
    tiktok: "",
    otherSocialMedia: "https://li.sten.to/sijya_younghate",
    linkToPreviousWork: "https://li.sten.to/sijya_younghate\nhttps://sijya.bandcamp.com",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 18,
    mediumGigsCount: 8,
    largeGigsCount: 0,
    gigScore: 34,
  },
  {
    id: "99",
    artistName: "Hena",
    preferredName: "Hena Sharma",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "Music Artist / Fashion Designer",
    genre: "alternative/indie/r&b",
    contactDetails: "hena-sharma@hotmail.com / 07769275430",
    instagram: "https://www.instagram.com/rasa.ldn/",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "https://open.spotify.com/artist/6EGh1ngCgfXWjmClmYHmYU?si=tlqL0qLqSG2HBQQQpkWYAA",
    linkToPreviousWork: "https://open.spotify.com/artist/6EGh1ngCgfXWjmClmYHmYU?si=tlqL0qLqSG2HBQQQpkWYAA",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 7,
    mediumGigsCount: 2,
    largeGigsCount: 0,
    gigScore: 11,
  },
  {
    id: "100",
    artistName: "Ruuz",
    preferredName: "Usman Mahmood",
    preferredPronouns: "",
    heritage: "",
    location: "London/ Dubai",
    outsideUK: "Dubai",
    typeOfAct: "DJ/ Promoter",
    genre: "Urban, UKG, house, funky, Bassline, grime, desi, afro",
    contactDetails: "7479680352",
    instagram: "https://www.instagram.com/ruuzthedj/",
    soundcloud: "https://soundcloud.com/ruuz12",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://www.instagram.com/ruuzthedj/\nhttps://soundcloud.com/ruuz12",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 0,
    mediumGigsCount: 3,
    largeGigsCount: 2,
    gigScore: 12,
  },
  {
    id: "101",
    artistName: "Izzet Garvey",
    preferredName: "Harvey Shergill",
    preferredPronouns: "",
    heritage: "",
    location: "Leicester",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "UK CLUB, BREAKS",
    contactDetails: "7415067064",
    instagram: "instagram.com/lowertone",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "instagram.com/lowertone",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 10,
    mediumGigsCount: 8,
    largeGigsCount: 0,
    gigScore: 26,
  },
  {
    id: "102",
    artistName: "WVRM POOL",
    preferredName: "Timothy Ezekiel",
    preferredPronouns: "",
    heritage: "",
    location: "London, UK",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "Techno, Hard Groove, Trance",
    contactDetails: "",
    instagram: "",
    soundcloud: "https://on.soundcloud.com/uspDs",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://on.soundcloud.com/uspDs",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 9,
    mediumGigsCount: 7,
    largeGigsCount: 4,
    gigScore: 35,
  },
  {
    id: "103",
    artistName: "zee",
    preferredName: "zee shah",
    preferredPronouns: "",
    heritage: "",
    location: "Croydon",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "grime, garage, jungle, house, indie-pop soul, bollywood, R&B",
    contactDetails: "7828336689",
    instagram: "",
    soundcloud: "https://www.mixcloud.com/z_double_e/i-eat-beats-for-breakfast/",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://www.mixcloud.com/z_double_e/i-eat-beats-for-breakfast/",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 8,
    mediumGigsCount: 8,
    largeGigsCount: 0,
    gigScore: 24,
  },
  {
    id: "104",
    artistName: "DJ Anjchilli",
    preferredName: "Anjali Dhulipala",
    preferredPronouns: "",
    heritage: "",
    location: "London, UK",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "UKG, Bollywood, Grime, Jungle, Baseline",
    contactDetails: "Phone no: 07983462500 Email:dhulipalaa@gmail.com",
    instagram: "",
    soundcloud: "https://on.soundcloud.com/XHQbrfZuQZ725Qbm6",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://on.soundcloud.com/XHQbrfZuQZ725Qbm6",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 14,
    mediumGigsCount: 2,
    largeGigsCount: 4,
    gigScore: 30,
  },
  {
    id: "105",
    artistName: "Saloni",
    preferredName: "Saloni Boyina",
    preferredPronouns: "",
    heritage: "",
    location: "Milton Keynes, UK",
    outsideUK: "",
    typeOfAct: "Artist",
    genre: "Pop, R&B, Desi",
    contactDetails: "Email: saloni@salonimusic.com   Number: +447943529459",
    instagram: "",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "Legacy (First Telugu/English Original) - http://www.salonimusic.com/legacy\n\nChali Mein (Women Empowerment Anthem) - http://www.salonimusic.com/chali-mein",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 18,
    mediumGigsCount: 2,
    largeGigsCount: 2,
    gigScore: 28,
  },
  {
    id: "106",
    artistName: "Lil Sur",
    preferredName: "Juhi Gupta",
    preferredPronouns: "",
    heritage: "",
    location: "San Francisco, CA",
    outsideUK: "San Francisco, CA",
    typeOfAct: "DJ, Graphic Designer",
    genre: "afro/latin/desi house, experimental club",
    contactDetails: "juhig01@gmail.com, +15109363437, @lilsurr",
    instagram: "@lilsurr",
    soundcloud: "https://soundcloud.com/littlesur",
    tiktok: "",
    otherSocialMedia: "juhi.design",
    linkToPreviousWork: "juhi.design / https://soundcloud.com/littlesur",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 3,
    mediumGigsCount: 7,
    largeGigsCount: 4,
    gigScore: 29,
  },
  {
    id: "107",
    artistName: "The Bass Injector",
    preferredName: "Ariel Remy Nurpuri",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ, producer, promoter, label owner, A&R, video editor",
    genre: "The whole spectrum of the old skool UK sound",
    contactDetails: "7757883615",
    instagram: "https://instagram.com/singularity.uk",
    soundcloud: "https://on.soundcloud.com/FqYS6",
    tiktok: "",
    otherSocialMedia: "https://instagram.com/demolitionsquadron\nhttps://instagram.com/racket.recordings\nhttps://instagram.com/notorioussteppaz",
    linkToPreviousWork: "https://on.soundcloud.com/FqYS6\n\nhttps://instagram.com/singularity.uk\n\nhttps://instagram.com/demolitionsquadron\n\nhttps://instagram.com/racket.recordings\n\nhttps://instagram.com/notorioussteppaz",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 6,
    mediumGigsCount: 10,
    largeGigsCount: 2,
    gigScore: 32,
  },
  {
    id: "108",
    artistName: "IYRE",
    preferredName: "Sasith Gamage",
    preferredPronouns: "",
    heritage: "",
    location: "Colombo/Sri Lanka - London/UK",
    outsideUK: "Colombo, Sri Lanka",
    typeOfAct: "Drum and Bass producer/DJ",
    genre: "Drum and Bass",
    contactDetails: "iyrednb@gmail.com/leah@theboom.live",
    instagram: "",
    soundcloud: "https://linktr.ee/IYREdnb",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://linktr.ee/IYREdnb",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 1,
    mediumGigsCount: 6,
    largeGigsCount: 0,
    gigScore: 13,
  },
  {
    id: "109",
    artistName: "Sattam",
    preferredName: "Sattam Rahman",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ/Producer",
    genre: "House, garage, electro, trance",
    contactDetails: "7939686959",
    instagram: "",
    soundcloud: "https://open.spotify.com/artist/6iyc6BGLOwF8ZZIfcaLVP7?si=moBFdQE8TAiTtD4SUivsfQ",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://open.spotify.com/artist/6iyc6BGLOwF8ZZIfcaLVP7?si=moBFdQE8TAiTtD4SUivsfQ",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 3,
    mediumGigsCount: 10,
    largeGigsCount: 0,
    gigScore: 23,
  },
  {
    id: "110",
    artistName: "Karan Ajmani",
    preferredName: "Karan Ajmani",
    preferredPronouns: "",
    heritage: "",
    location: "Cambridge, UK",
    outsideUK: "",
    typeOfAct: "Music Producer / DJ",
    genre: "Progressive House, Melodic Techno, Dub Techno, Detroit Techno",
    contactDetails: "",
    instagram: "",
    soundcloud: "https://soundcloud.com/karanajmanii/beyong-the-horizon-04-transmission-05-may-2023",
    tiktok: "",
    otherSocialMedia: "https://open.spotify.com/artist/6bgAiG7HkofvuRsCAuDGy3?si=iemRzDgvRa-tgam_c8fUZg",
    linkToPreviousWork: "https://open.spotify.com/artist/6bgAiG7HkofvuRsCAuDGy3?si=iemRzDgvRa-tgam_c8fUZg\n\nhttps://soundcloud.com/karanajmanii/beyong-the-horizon-04-transmission-05-may-2023",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 13,
    mediumGigsCount: 9,
    largeGigsCount: 4,
    gigScore: 43,
  },
  {
    id: "111",
    artistName: "Smoove Kriminal",
    preferredName: "Satpal Singh",
    preferredPronouns: "",
    heritage: "",
    location: "London (East)",
    outsideUK: "",
    typeOfAct: "DJ / Producer / Radio Host",
    genre: "UK Funky, Amapiano, UK Garage, House (Various), Jungle, Vinyl Sets, too!",
    contactDetails: "smoovekriminal@hotmail.co.uk",
    instagram: "",
    soundcloud: "https://linktr.ee/SmooveKriminal",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://linktr.ee/SmooveKriminal",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 1,
    mediumGigsCount: 10,
    largeGigsCount: 4,
    gigScore: 33,
  },
  {
    id: "112",
    artistName: "SAFIYA",
    preferredName: "Safiya Bashir",
    preferredPronouns: "",
    heritage: "",
    location: "Amsterdam/Bristol",
    outsideUK: "Amsterdam",
    typeOfAct: "DJ",
    genre: "Bollywood, Afrodesi, Arab, Amapiano, UK Funky,  Garage.",
    contactDetails: "31648276247",
    instagram: "https://www.instagram.com/safiya.haneen/?hl=en",
    soundcloud: "https://soundcloud.com/safiya-bashir-273807362",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.com/safiya-bashir-273807362\nhttps://www.instagram.com/safiya.haneen/?hl=en",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 19,
    mediumGigsCount: 1,
    largeGigsCount: 2,
    gigScore: 27,
  },
  {
    id: "113",
    artistName: "jjamz",
    preferredName: "Jamaal  Johnson",
    preferredPronouns: "",
    heritage: "",
    location: "London (New York until mid Nov)",
    outsideUK: "New York",
    typeOfAct: "DJ",
    genre: "UK funky, Broken beat, Soulful House, Amapiano",
    contactDetails: "447426417967",
    instagram: "",
    soundcloud: "https://linktr.ee/jjamz",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://linktr.ee/jjamz",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 16,
    mediumGigsCount: 2,
    largeGigsCount: 2,
    gigScore: 26,
  },
  {
    id: "114",
    artistName: "Abibi",
    preferredName: "Abeera",
    preferredPronouns: "",
    heritage: "",
    location: "Berlin",
    outsideUK: "Berlin",
    typeOfAct: "DJ/Event organiser/Writer",
    genre: "Bass, experimental, UK, dance, traditional",
    contactDetails: "abibidoinmusic@gmail.com",
    instagram: "https://www.instagram.com/not.abibi/",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "https://refugeworldwide.com/radio/daytimers-abibi-21-jun-2023",
    linkToPreviousWork: "https://www.youtube.com/watch?v=CKW4bzn_mDU&ab_channel=KeepHush; https://refugeworldwide.com/radio/daytimers-abibi-21-jun-2023;\nhttps://www.youtube.com/results?search_query=abibi+hor+berlin;\nhttps://www.instagram.com/not.abibi/",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 19,
    mediumGigsCount: 4,
    largeGigsCount: 4,
    gigScore: 39,
  },
  {
    id: "115",
    artistName: "Kalbaisakhi",
    preferredName: "Vibhu Singh",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "Producer-DJ",
    genre: "House, Afrobeats, Amapiano, UK Funky, Baile Funk, Grime, Dubstep, Jungle, Hip-Hop",
    contactDetails: "447423665985",
    instagram: "",
    soundcloud: "https://soundcloud.com/kalbaisakhimusic",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.com/kalbaisakhimusic\n\nhttps://drive.google.com/file/d/15NmKKQie-4L2KDniZfwVAzyuKY_zBArF/view?usp=drive_link\n\nhttps://youtu.be/tO5I8yRk57I?si=U41-3M9GvAkatJsp\n\nhttps://youtu.be/Q_MbWLuNmIw?si=4cw3vPQsW4BhBGZR",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 12,
    mediumGigsCount: 5,
    largeGigsCount: 0,
    gigScore: 22,
  },
  {
    id: "116",
    artistName: "adnan afghani",
    preferredName: "Adnan",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "Sound Artist / DJ / Producer",
    genre: "Ambient / Glitch / Jungle / IDM / Ai",
    contactDetails: "adnany1198@gmail.com",
    instagram: "",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://docs.google.com/document/d/1p0PTNNINo9n8J4LG_PKugKHVgw-O6nZO6svy0_wqzdc/edit?usp=sharing",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 20,
    mediumGigsCount: 10,
    largeGigsCount: 4,
    gigScore: 52,
  },
  {
    id: "117",
    artistName: "Daskaran",
    preferredName: "Rohin",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "DJ/producer",
    genre: "Techno, trap",
    contactDetails: "daskaran.music@gmail.com",
    instagram: "",
    soundcloud: "https://on.soundcloud.com/D6pxS",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://on.soundcloud.com/D6pxS\n\nhttps://on.soundcloud.com/mQrSY",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 0,
    mediumGigsCount: 3,
    largeGigsCount: 0,
    gigScore: 6,
  },
  {
    id: "118",
    artistName: "JG:MC",
    preferredName: "Jay Ghelani",
    preferredPronouns: "",
    heritage: "",
    location: "Leicester",
    outsideUK: "",
    typeOfAct: "MC (Dnb, UKG + 140)",
    genre: "Dnb & UKG",
    contactDetails: "07903 393337",
    instagram: "",
    soundcloud: "https://soundcloud.com/efanuk/bigga-man-sound-feat-jgmc-demo-1/s-SQiju6JFXXT",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://soundcloud.com/efanuk/bigga-man-sound-feat-jgmc-demo-1/s-SQiju6JFXXT\n\nhttps://m.soundcloud.com/sakuraselections/mavros-jgmc-selecta",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 6,
    mediumGigsCount: 10,
    largeGigsCount: 4,
    gigScore: 38,
  },
  {
    id: "119",
    artistName: "Jaan-e-Haseena",
    preferredName: 'Hussain "Haseena" Abbas Zaidi',
    preferredPronouns: "",
    heritage: "",
    location: "Lahore, Pakistan ; New York, NY",
    outsideUK: "Lahore, Pakistan ; New York, NY",
    typeOfAct: "I am a DJ, Creative Director, Event Curator, Experimental Hip-Hop Producer, and Performer-Activist.",
    genre: "Electro-Punk, Mujra/Femme-Pakistani Commerical/Classical, Hip-Hop",
    contactDetails: "",
    instagram: "https://www.instagram.com/zenaankhana/",
    soundcloud: "https://soundcloud.com/jaanehaseena/premiere-infinity-records-the-modran-moorat",
    tiktok: "",
    otherSocialMedia: "https://open.spotify.com/artist/1Cl9ZPPzWnEM7ockxRZuKh?si=d--xR_JXTxi-gMvXF6vLCw",
    linkToPreviousWork: "Mix: https://soundcloud.com/jaanehaseena/premiere-infinity-records-the-modran-moorat\nSpotify: https://open.spotify.com/artist/1Cl9ZPPzWnEM7ockxRZuKh?si=d--xR_JXTxi-gMvXF6vLCw\nCreative Direction + Event Curation: https://www.instagram.com/zenaankhana/",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 7,
    mediumGigsCount: 5,
    largeGigsCount: 2,
    gigScore: 23,
  },
  {
    id: "120",
    artistName: "early riser",
    preferredName: "zee shah",
    preferredPronouns: "",
    heritage: "",
    location: "South East London",
    outsideUK: "",
    typeOfAct: "DJ",
    genre: "Grime, Garage, House, Jungle, D&B, Electronica, Alternative, Bollywood,",
    contactDetails: "7961656786",
    instagram: "",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "N/A",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 18,
    mediumGigsCount: 5,
    largeGigsCount: 0,
    gigScore: 28,
  },
  {
    id: "121",
    artistName: "SHIR.IN",
    preferredName: "Shirin Naveed",
    preferredPronouns: "",
    heritage: "",
    location: "South East London / Brum",
    outsideUK: "",
    typeOfAct: "DJ / Creative Producer and Visual Artist",
    genre: "140, dubstep, jungle, edits, breaks, baile, funky,",
    contactDetails: "",
    instagram: "",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 15,
    mediumGigsCount: 4,
    largeGigsCount: 2,
    gigScore: 29,
  },
  {
    id: "122",
    artistName: "NEO 10Y",
    preferredName: "NEO 10Y / Nikhil",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "Recording artist / multi disciplinary artist",
    genre: "Genre expansive",
    contactDetails: "neotenymusic@gmail.com // 07747896869",
    instagram: "",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "www.bio.site/neo10y",
    linkToPreviousWork: "www.bio.site/neo10y // https://open.spotify.com/artist/3G1V2jfTZO61Hs3dX7ilrA?si=tgDW3irMQWW0kEwChTR1aQ",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 16,
    mediumGigsCount: 8,
    largeGigsCount: 0,
    gigScore: 32,
  },
  {
    id: "123",
    artistName: "Mistry",
    preferredName: "Hitesh Mistry",
    preferredPronouns: "",
    heritage: "",
    location: "London (North)",
    outsideUK: "",
    typeOfAct: "Singer songwriter & producer",
    genre: "Alternative RnB",
    contactDetails: "7916100102",
    instagram: "https://www.instagram.com/mistryofficial/",
    soundcloud: "",
    tiktok: "https://www.tiktok.com/@mistryofficial_?lang=en",
    otherSocialMedia: "https://open.spotify.com/artist/22EOuWI4bRUfaCfmEj04pt?si=H3V_JhNzS52iTIUCJP4Xeg",
    linkToPreviousWork: "Check out Mistry's Socials & Music here:\nSpotify - https://open.spotify.com/artist/22EOuWI4bRUfaCfmEj04pt?si=H3V_JhNzS52iTIUCJP4Xeg \nInstagram - https://www.instagram.com/mistryofficial/\nYouTube - https://www.youtube.com/c/MistryOfficial \nTik Tok - https://www.tiktok.com/@mistryofficial_?lang=en",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 8,
    mediumGigsCount: 0,
    largeGigsCount: 2,
    gigScore: 14,
  },
  {
    id: "124",
    artistName: "Webmoms / Karum Cooper",
    preferredName: "Karum Cooper",
    preferredPronouns: "",
    heritage: "",
    location: "Cornwall, UK",
    outsideUK: "",
    typeOfAct: "Music producer, songwriter, multi instrumentalist, poet and music artist",
    genre: "RnB, Neo Soul, Hip Hop, Rap, Lofi, jazzhop, instrumental beats",
    contactDetails: "7905774940",
    instagram: "",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "https://open.spotify.com/artist/2ol5Xy14VMiqF9KjzW41c4",
    linkToPreviousWork: "https://open.spotify.com/artist/2ol5Xy14VMiqF9KjzW41c4",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 16,
    mediumGigsCount: 0,
    largeGigsCount: 4,
    gigScore: 28,
  },
  {
    id: "125",
    artistName: "ABRZY",
    preferredName: "Abid Rahman",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "Artist",
    genre: "Hip-Hop/Rap",
    contactDetails: "abrzymusic@gmail.com",
    instagram: "",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "https://open.spotify.com/artist/0GIxnPuJrbOyBfyYkMzJRo?si=VugEPW_xTFOroj_TiH7rdw",
    linkToPreviousWork: "https://drive.google.com/file/d/1GfFfRifqniYyvcsRAhr8XhC-PY4kIYLE/view?usp=sharing\n\nWebsite: www.abrzy.com\n\nhttps://open.spotify.com/artist/0GIxnPuJrbOyBfyYkMzJRo?si=VugEPW_xTFOroj_TiH7rdw",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 6,
    mediumGigsCount: 9,
    largeGigsCount: 4,
    gigScore: 36,
  },
  {
    id: "126",
    artistName: "Ishani Jasmin",
    preferredName: "Ishani Jasmin",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "Facilitator (music), musician, poet, writer, events organiser",
    genre: "punk, rock, alternative",
    contactDetails: "07954335688 / ishanijasmin@gmail.com",
    instagram: "instagram.com/firsttimersfest",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "breakuphaircut.bandcamp.com\ngirlsrocklondon.com\ndecolonisefest.co.uk",
    linkToPreviousWork: "breakuphaircut.bandcamp.com\ngirlsrocklondon.com\ndecolonisefest.co.uk\ninstagram.com/firsttimersfest",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 5,
    mediumGigsCount: 2,
    largeGigsCount: 0,
    gigScore: 9,
  },
  {
    id: "127",
    artistName: "Raul Made It",
    preferredName: "Raul Plahe",
    preferredPronouns: "",
    heritage: "",
    location: "London",
    outsideUK: "",
    typeOfAct: "Producer",
    genre: "Pop, house, garage",
    contactDetails: "7779944786",
    instagram: "",
    soundcloud: "https://s.disco.ac/pppjscycentm",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://s.disco.ac/pppjscycentm",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 0,
    mediumGigsCount: 2,
    largeGigsCount: 0,
    gigScore: 4,
  },
  {
    id: "128",
    artistName: "Vidya",
    preferredName: "Vidya Divakaran",
    preferredPronouns: "",
    heritage: "",
    location: "Ilford",
    outsideUK: "",
    typeOfAct: "Comedian and theatre maker, Event host and budding DJ - also a graphic designer",
    genre: "",
    contactDetails: "vidyadiva.1@gmail.com",
    instagram: "https://www.instagram.com/vidyafunnies/",
    soundcloud: "",
    tiktok: "",
    otherSocialMedia: "",
    linkToPreviousWork: "https://www.instagram.com/vidyafunnies/",
    mostRecentEvent: "",
    mostRecentEventDate: "",
    smallGigsCount: 0,
    mediumGigsCount: 2,
    largeGigsCount: 0,
    gigScore: 4,
  },
];

export function searchDJs(query: string, djs: DJ[]): DJ[] {
  if (!query.trim()) return djs;

  const lowerQuery = query.toLowerCase();
  return djs.filter(
    (dj) =>
      dj.artistName.toLowerCase().includes(lowerQuery) ||
      dj.preferredName.toLowerCase().includes(lowerQuery) ||
      dj.location.toLowerCase().includes(lowerQuery) ||
      dj.typeOfAct.toLowerCase().includes(lowerQuery) ||
      dj.genre.toLowerCase().includes(lowerQuery) ||
      dj.heritage.toLowerCase().includes(lowerQuery)
  );
}

export function addDJ(dj: Omit<DJ, "id">): DJ {
  const newDJ: DJ = {
    ...dj,
    id: Date.now().toString(),
  };
  return newDJ;
}
