import { ApiEndpoint } from "./types";
import { GREENROOM_API_BASE } from "@/config/greenroomApi";

const BASE_URL = GREENROOM_API_BASE;

export const API_ENDPOINTS: ApiEndpoint[] = [
  // Health Check
  {
    id: "health-basic",
    name: "Basic Health Check",
    method: "GET",
    path: "/{service}/health/",
    category: "Health Check",
    description: "Basic health check for a service",
    requiresId: true,
  },
  {
    id: "health-detailed",
    name: "Detailed Health Check",
    method: "GET",
    path: "/{service}/health/detailed/",
    category: "Health Check",
    description: "Detailed health check with system checks",
    requiresId: true,
  },
  // Artists
  {
    id: "artists-list",
    name: "List All Artists",
    method: "GET",
    path: "/artists/",
    category: "Artists",
    queryParams: [
      { name: "is_active", required: false },
      { name: "is_collective_member", required: false },
    ],
  },
  {
    id: "artists-find",
    name: "Find Artist by Name",
    method: "GET",
    path: "/artists/find/",
    category: "Artists",
    queryParams: [{ name: "name", required: true }],
  },
  {
    id: "artists-get",
    name: "Get Artist by ID",
    method: "GET",
    path: "/artists/{id}/",
    category: "Artists",
    requiresId: true,
  },
  {
    id: "artists-create",
    name: "Create Artist",
    method: "POST",
    path: "/artists/create/",
    category: "Artists",
    bodyFields: [
      { name: "artist_name", required: true, type: "string" },
      { name: "preferred_name", required: false, type: "string" },
      { name: "pronouns", required: false, type: "string" },
      { name: "is_active", required: false, type: "boolean" },
      { name: "is_collective_member", required: false, type: "boolean" },
    ],
  },
  {
    id: "artists-update",
    name: "Update Artist",
    method: "PATCH",
    path: "/artists/{id}/update/",
    category: "Artists",
    requiresId: true,
    bodyFields: [
      { name: "artist_name", required: false, type: "string" },
      { name: "preferred_name", required: false, type: "string" },
      { name: "bio", required: false, type: "string" },
    ],
  },
  {
    id: "artists-delete",
    name: "Delete Artist",
    method: "DELETE",
    path: "/artists/{id}/delete/",
    category: "Artists",
    requiresId: true,
  },
  // Events
  {
    id: "events-list",
    name: "List All Events",
    method: "GET",
    path: "/events/",
    category: "Events",
    queryParams: [
      { name: "start_date", required: false },
      { name: "end_date", required: false },
    ],
  },
  {
    id: "events-get",
    name: "Get Event by ID",
    method: "GET",
    path: "/events/{id}/",
    category: "Events",
    requiresId: true,
  },
  {
    id: "events-create",
    name: "Create Event",
    method: "POST",
    path: "/events/create/",
    category: "Events",
    bodyFields: [
      { name: "name", required: true, type: "string" },
      { name: "event_date", required: true, type: "string" },
      { name: "gig_size_id", required: true, type: "number" },
      { name: "city", required: false, type: "string" },
      { name: "country", required: false, type: "string" },
    ],
  },
  {
    id: "events-update",
    name: "Update Event",
    method: "PATCH",
    path: "/events/{id}/update/",
    category: "Events",
    requiresId: true,
    bodyFields: [
      { name: "name", required: false, type: "string" },
      { name: "event_date", required: false, type: "string" },
      { name: "city", required: false, type: "string" },
    ],
  },
  {
    id: "events-delete",
    name: "Delete Event",
    method: "DELETE",
    path: "/events/{id}/delete/",
    category: "Events",
    requiresId: true,
  },
  // Bookings
  {
    id: "bookings-list",
    name: "List All Bookings",
    method: "GET",
    path: "/bookings/",
    category: "Bookings",
    queryParams: [
      { name: "artist_id", required: false },
      { name: "start_date", required: false },
      { name: "end_date", required: false },
    ],
  },
  {
    id: "bookings-get",
    name: "Get Booking by ID",
    method: "GET",
    path: "/bookings/{id}/",
    category: "Bookings",
    requiresId: true,
  },
  {
    id: "bookings-create",
    name: "Create Booking",
    method: "POST",
    path: "/bookings/create/",
    category: "Bookings",
    bodyFields: [
      { name: "artist_id", required: true, type: "number" },
      { name: "event_id", required: true, type: "number" },
      { name: "status", required: false, type: "string" },
      { name: "agreed_fee", required: false, type: "number" },
    ],
  },
  {
    id: "bookings-update",
    name: "Update Booking",
    method: "PATCH",
    path: "/bookings/{id}/update/",
    category: "Bookings",
    requiresId: true,
    bodyFields: [
      { name: "status", required: false, type: "string" },
      { name: "agreed_fee", required: false, type: "number" },
    ],
  },
  {
    id: "bookings-delete",
    name: "Delete Booking",
    method: "DELETE",
    path: "/bookings/{id}/delete/",
    category: "Bookings",
    requiresId: true,
  },
  // Projects
  {
    id: "projects-list",
    name: "List All Projects",
    method: "GET",
    path: "/projects/",
    category: "Projects",
    queryParams: [{ name: "status", required: false }],
  },
  {
    id: "projects-get",
    name: "Get Project by ID",
    method: "GET",
    path: "/projects/{id}/",
    category: "Projects",
    requiresId: true,
  },
  {
    id: "projects-create",
    name: "Create Project",
    method: "POST",
    path: "/projects/create/",
    category: "Projects",
    bodyFields: [
      { name: "name", required: true, type: "string" },
      { name: "status", required: true, type: "string" },
      { name: "description", required: false, type: "string" },
      { name: "lead_artist_id", required: false, type: "number" },
    ],
  },
  {
    id: "projects-update",
    name: "Update Project",
    method: "PATCH",
    path: "/projects/{id}/update/",
    category: "Projects",
    requiresId: true,
    bodyFields: [
      { name: "name", required: false, type: "string" },
      { name: "status", required: false, type: "string" },
    ],
  },
  {
    id: "projects-delete",
    name: "Delete Project",
    method: "DELETE",
    path: "/projects/{id}/delete/",
    category: "Projects",
    requiresId: true,
  },
  // Payments
  {
    id: "payments-list",
    name: "List All Payments",
    method: "GET",
    path: "/payments/",
    category: "Payments",
    queryParams: [
      { name: "artist_id", required: false },
      { name: "project_id", required: false },
    ],
  },
  {
    id: "payments-get",
    name: "Get Payment by ID",
    method: "GET",
    path: "/payments/{id}/",
    category: "Payments",
    requiresId: true,
  },
  {
    id: "payments-create",
    name: "Create Payment",
    method: "POST",
    path: "/payments/create/",
    category: "Payments",
    bodyFields: [
      { name: "artist_id", required: true, type: "number" },
      { name: "amount", required: true, type: "number" },
      { name: "status", required: true, type: "string" },
      { name: "currency", required: false, type: "string" },
    ],
  },
  {
    id: "payments-update",
    name: "Update Payment",
    method: "PATCH",
    path: "/payments/{id}/update/",
    category: "Payments",
    requiresId: true,
    bodyFields: [
      { name: "status", required: false, type: "string" },
      { name: "amount", required: false, type: "number" },
    ],
  },
  {
    id: "payments-delete",
    name: "Delete Payment",
    method: "DELETE",
    path: "/payments/{id}/delete/",
    category: "Payments",
    requiresId: true,
  },
  // Project Tasks
  {
    id: "projects-tasks-list",
    name: "List Project Tasks",
    method: "GET",
    path: "/projects/{id}/tasks/",
    category: "Project Tasks",
    requiresId: true,
  },
  {
    id: "projects-tasks-create",
    name: "Create Project Task",
    method: "POST",
    path: "/projects/{id}/tasks/create/",
    category: "Project Tasks",
    requiresId: true,
    bodyFields: [
      { name: "title", required: true, type: "string" },
      { name: "description", required: false, type: "string" },
      { name: "status", required: false, type: "string" },
      { name: "priority", required: false, type: "string" },
      { name: "assignee_user_id", required: false, type: "number" },
      { name: "due_date", required: false, type: "string" },
    ],
  },
  {
    id: "tasks-update",
    name: "Update Task",
    method: "PATCH",
    path: "/tasks/{id}/update/",
    category: "Project Tasks",
    requiresId: true,
    bodyFields: [
      { name: "title", required: false, type: "string" },
      { name: "description", required: false, type: "string" },
      { name: "status", required: false, type: "string" },
      { name: "priority", required: false, type: "string" },
      { name: "assignee_user_id", required: false, type: "number" },
      { name: "due_date", required: false, type: "string" },
    ],
  },
  {
    id: "tasks-delete",
    name: "Delete Task",
    method: "DELETE",
    path: "/tasks/{id}/delete/",
    category: "Project Tasks",
    requiresId: true,
  },
  // Project Wrapups
  {
    id: "projects-wrapup-get",
    name: "Get Project Wrapup",
    method: "GET",
    path: "/projects/{id}/wrapup/",
    category: "Project Wrapups",
    requiresId: true,
  },
  {
    id: "projects-wrapup-create",
    name: "Create Project Wrapup",
    method: "POST",
    path: "/projects/{id}/wrapup/create/",
    category: "Project Wrapups",
    requiresId: true,
    bodyFields: [
      { name: "summary", required: false, type: "string" },
      { name: "lessons_learned", required: false, type: "string" },
      { name: "wrapup_by_user_id", required: false, type: "number" },
    ],
  },
  {
    id: "projects-wrapup-update",
    name: "Update Project Wrapup",
    method: "PATCH",
    path: "/projects/{id}/wrapup/update/",
    category: "Project Wrapups",
    requiresId: true,
    bodyFields: [
      { name: "summary", required: false, type: "string" },
      { name: "lessons_learned", required: false, type: "string" },
      { name: "wrapup_by_user_id", required: false, type: "number" },
    ],
  },
  {
    id: "projects-wrapup-delete",
    name: "Delete Project Wrapup",
    method: "DELETE",
    path: "/projects/{id}/wrapup/delete/",
    category: "Project Wrapups",
    requiresId: true,
  },
  // Advanced Project Operations
  {
    id: "projects-assign-team",
    name: "Assign Team to Project",
    method: "POST",
    path: "/projects/{id}/assign-team/",
    category: "Projects",
    requiresId: true,
    bodyFields: [
      { name: "team_members", required: true, type: "array" },
    ],
  },
  {
    id: "projects-update-status",
    name: "Update Project Status",
    method: "PATCH",
    path: "/projects/{id}/update-status/",
    category: "Projects",
    requiresId: true,
    bodyFields: [
      { name: "status", required: false, type: "string" },
      { name: "description", required: false, type: "string" },
      { name: "end_date", required: false, type: "string" },
    ],
  },
  {
    id: "projects-archive",
    name: "Archive Project",
    method: "POST",
    path: "/projects/{id}/archive/",
    category: "Projects",
    requiresId: true,
  },
  {
    id: "artists-projects",
    name: "Get Artist Projects",
    method: "GET",
    path: "/artists/{id}/projects/",
    category: "Artists",
    requiresId: true,
  },
  // Pitches
  {
    id: "pitches-list",
    name: "List All Pitches",
    method: "GET",
    path: "/pitches/",
    category: "Pitches",
  },
  {
    id: "pitches-get",
    name: "Get Pitch by ID",
    method: "GET",
    path: "/pitches/{id}/",
    category: "Pitches",
    requiresId: true,
  },
  {
    id: "pitches-create",
    name: "Create Pitch",
    method: "POST",
    path: "/pitches/create/",
    category: "Pitches",
    bodyFields: [
      { name: "submitter_user_id", required: true, type: "number" },
      { name: "title", required: true, type: "string" },
      { name: "description", required: false, type: "string" },
      { name: "status", required: false, type: "string" },
      { name: "project_id", required: false, type: "number" },
    ],
  },
  {
    id: "pitches-update",
    name: "Update Pitch",
    method: "PATCH",
    path: "/pitches/{id}/update/",
    category: "Pitches",
    requiresId: true,
    bodyFields: [
      { name: "title", required: false, type: "string" },
      { name: "description", required: false, type: "string" },
      { name: "status", required: false, type: "string" },
      { name: "submitter_user_id", required: false, type: "number" },
      { name: "project_id", required: false, type: "number" },
    ],
  },
  {
    id: "pitches-delete",
    name: "Delete Pitch",
    method: "DELETE",
    path: "/pitches/{id}/delete/",
    category: "Pitches",
    requiresId: true,
  },
  {
    id: "pitches-vote",
    name: "Vote on Pitch",
    method: "POST",
    path: "/pitches/{id}/vote/",
    category: "Pitches",
    requiresId: true,
    bodyFields: [
      { name: "user_id", required: true, type: "number" },
      { name: "vote_value", required: true, type: "number" },
      { name: "comment", required: false, type: "string" },
    ],
  },
  {
    id: "pitches-move-to-project",
    name: "Move Pitch to Project",
    method: "POST",
    path: "/pitches/{id}/move-to-project/",
    category: "Pitches",
    requiresId: true,
    bodyFields: [
      { name: "project_id", required: true, type: "number" },
    ],
  },
  {
    id: "pitches-close",
    name: "Close Pitch",
    method: "POST",
    path: "/pitches/{id}/close/",
    category: "Pitches",
    requiresId: true,
    bodyFields: [
      { name: "status", required: false, type: "string" },
    ],
  },
  {
    id: "pitches-add-comment",
    name: "Add Pitch Comment",
    method: "POST",
    path: "/pitches/{id}/comments/",
    category: "Pitches",
    requiresId: true,
    bodyFields: [
      { name: "user_id", required: true, type: "number" },
      { name: "comment", required: true, type: "string" },
      { name: "parent_comment_id", required: false, type: "number" },
    ],
  },
  // Analytics
  {
    id: "analytics-gig-scores",
    name: "Get Gig Scores by Artist",
    method: "GET",
    path: "/analytics/gig-scores/",
    category: "Analytics",
  },
  {
    id: "analytics-artists-by-country",
    name: "Get Artists by Country",
    method: "GET",
    path: "/analytics/artists-by-country/",
    category: "Analytics",
    queryParams: [{ name: "country", required: true }],
  },
  {
    id: "analytics-artists-multiple-cities",
    name: "Get Artists in Multiple Cities",
    method: "GET",
    path: "/analytics/artists-multiple-cities/",
    category: "Analytics",
    queryParams: [{ name: "country", required: true }],
  },
];

export { BASE_URL };


