import { ApiEndpoint } from "./types";

const BASE_URL = "https://jzre02jvh9.execute-api.eu-west-2.amazonaws.com/api";

export const API_ENDPOINTS: ApiEndpoint[] = [
  // Health Check
  {
    id: "health-basic",
    name: "Basic Health Check",
    method: "GET",
    path: "/{service}/health/",
    category: "Health Check",
    description: "Basic health check for a service",
    requiresId: true,
  },
  {
    id: "health-detailed",
    name: "Detailed Health Check",
    method: "GET",
    path: "/{service}/health/detailed/",
    category: "Health Check",
    description: "Detailed health check with system checks",
    requiresId: true,
  },
  // Artists
  {
    id: "artists-list",
    name: "List All Artists",
    method: "GET",
    path: "/artists/",
    category: "Artists",
    queryParams: [
      { name: "is_active", required: false },
      { name: "is_collective_member", required: false },
    ],
  },
  {
    id: "artists-find",
    name: "Find Artist by Name",
    method: "GET",
    path: "/artists/find/",
    category: "Artists",
    queryParams: [{ name: "name", required: true }],
  },
  {
    id: "artists-get",
    name: "Get Artist by ID",
    method: "GET",
    path: "/artists/{id}/",
    category: "Artists",
    requiresId: true,
  },
  {
    id: "artists-create",
    name: "Create Artist",
    method: "POST",
    path: "/artists/create/",
    category: "Artists",
    bodyFields: [
      { name: "artist_name", required: true, type: "string" },
      { name: "preferred_name", required: false, type: "string" },
      { name: "pronouns", required: false, type: "string" },
      { name: "is_active", required: false, type: "boolean" },
      { name: "is_collective_member", required: false, type: "boolean" },
    ],
  },
  {
    id: "artists-update",
    name: "Update Artist",
    method: "PATCH",
    path: "/artists/{id}/update/",
    category: "Artists",
    requiresId: true,
    bodyFields: [
      { name: "artist_name", required: false, type: "string" },
      { name: "preferred_name", required: false, type: "string" },
      { name: "bio", required: false, type: "string" },
    ],
  },
  {
    id: "artists-delete",
    name: "Delete Artist",
    method: "DELETE",
    path: "/artists/{id}/delete/",
    category: "Artists",
    requiresId: true,
  },
  // Events
  {
    id: "events-list",
    name: "List All Events",
    method: "GET",
    path: "/events/",
    category: "Events",
    queryParams: [
      { name: "start_date", required: false },
      { name: "end_date", required: false },
    ],
  },
  {
    id: "events-get",
    name: "Get Event by ID",
    method: "GET",
    path: "/events/{id}/",
    category: "Events",
    requiresId: true,
  },
  {
    id: "events-create",
    name: "Create Event",
    method: "POST",
    path: "/events/create/",
    category: "Events",
    bodyFields: [
      { name: "name", required: true, type: "string" },
      { name: "event_date", required: true, type: "string" },
      { name: "gig_size_id", required: true, type: "number" },
      { name: "city", required: false, type: "string" },
      { name: "country", required: false, type: "string" },
    ],
  },
  {
    id: "events-update",
    name: "Update Event",
    method: "PATCH",
    path: "/events/{id}/update/",
    category: "Events",
    requiresId: true,
    bodyFields: [
      { name: "name", required: false, type: "string" },
      { name: "event_date", required: false, type: "string" },
      { name: "city", required: false, type: "string" },
    ],
  },
  {
    id: "events-delete",
    name: "Delete Event",
    method: "DELETE",
    path: "/events/{id}/delete/",
    category: "Events",
    requiresId: true,
  },
  // Bookings
  {
    id: "bookings-list",
    name: "List All Bookings",
    method: "GET",
    path: "/bookings/",
    category: "Bookings",
    queryParams: [
      { name: "artist_id", required: false },
      { name: "start_date", required: false },
      { name: "end_date", required: false },
    ],
  },
  {
    id: "bookings-get",
    name: "Get Booking by ID",
    method: "GET",
    path: "/bookings/{id}/",
    category: "Bookings",
    requiresId: true,
  },
  {
    id: "bookings-create",
    name: "Create Booking",
    method: "POST",
    path: "/bookings/create/",
    category: "Bookings",
    bodyFields: [
      { name: "artist_id", required: true, type: "number" },
      { name: "event_id", required: true, type: "number" },
      { name: "status", required: false, type: "string" },
      { name: "agreed_fee", required: false, type: "number" },
    ],
  },
  {
    id: "bookings-update",
    name: "Update Booking",
    method: "PATCH",
    path: "/bookings/{id}/update/",
    category: "Bookings",
    requiresId: true,
    bodyFields: [
      { name: "status", required: false, type: "string" },
      { name: "agreed_fee", required: false, type: "number" },
    ],
  },
  {
    id: "bookings-delete",
    name: "Delete Booking",
    method: "DELETE",
    path: "/bookings/{id}/delete/",
    category: "Bookings",
    requiresId: true,
  },
  // Projects
  {
    id: "projects-list",
    name: "List All Projects",
    method: "GET",
    path: "/projects/",
    category: "Projects",
    queryParams: [{ name: "status", required: false }],
  },
  {
    id: "projects-get",
    name: "Get Project by ID",
    method: "GET",
    path: "/projects/{id}/",
    category: "Projects",
    requiresId: true,
  },
  {
    id: "projects-create",
    name: "Create Project",
    method: "POST",
    path: "/projects/create/",
    category: "Projects",
    bodyFields: [
      { name: "name", required: true, type: "string" },
      { name: "status", required: true, type: "string" },
      { name: "description", required: false, type: "string" },
      { name: "lead_artist_id", required: false, type: "number" },
    ],
  },
  {
    id: "projects-update",
    name: "Update Project",
    method: "PATCH",
    path: "/projects/{id}/update/",
    category: "Projects",
    requiresId: true,
    bodyFields: [
      { name: "name", required: false, type: "string" },
      { name: "status", required: false, type: "string" },
    ],
  },
  {
    id: "projects-delete",
    name: "Delete Project",
    method: "DELETE",
    path: "/projects/{id}/delete/",
    category: "Projects",
    requiresId: true,
  },
  // Payments
  {
    id: "payments-list",
    name: "List All Payments",
    method: "GET",
    path: "/payments/",
    category: "Payments",
    queryParams: [
      { name: "artist_id", required: false },
      { name: "project_id", required: false },
    ],
  },
  {
    id: "payments-get",
    name: "Get Payment by ID",
    method: "GET",
    path: "/payments/{id}/",
    category: "Payments",
    requiresId: true,
  },
  {
    id: "payments-create",
    name: "Create Payment",
    method: "POST",
    path: "/payments/create/",
    category: "Payments",
    bodyFields: [
      { name: "artist_id", required: true, type: "number" },
      { name: "amount", required: true, type: "number" },
      { name: "status", required: true, type: "string" },
      { name: "currency", required: false, type: "string" },
    ],
  },
  {
    id: "payments-update",
    name: "Update Payment",
    method: "PATCH",
    path: "/payments/{id}/update/",
    category: "Payments",
    requiresId: true,
    bodyFields: [
      { name: "status", required: false, type: "string" },
      { name: "amount", required: false, type: "number" },
    ],
  },
  {
    id: "payments-delete",
    name: "Delete Payment",
    method: "DELETE",
    path: "/payments/{id}/delete/",
    category: "Payments",
    requiresId: true,
  },
  // Analytics
  {
    id: "analytics-gig-scores",
    name: "Get Gig Scores by Artist",
    method: "GET",
    path: "/analytics/gig-scores/",
    category: "Analytics",
  },
  {
    id: "analytics-artists-by-country",
    name: "Get Artists by Country",
    method: "GET",
    path: "/analytics/artists-by-country/",
    category: "Analytics",
    queryParams: [{ name: "country", required: true }],
  },
];

export { BASE_URL };


