export const appIds = [
  "finder",
  "soundboard",
  "internet-explorer",
  "chats",
  "textedit",
  "paint",
  "photo-booth",
  "minesweeper",
  "videos",
  "ipod",
  "synth",
  "pc",
  "terminal",
  "applet-viewer",
  "control-panels",
  "admin",
  "greenroom-admin",
  "incoming-offers",
  "active-projects",
  "pitch",
  "archive",
  "feedback",
] as const;

export type AppId = (typeof appIds)[number];
